/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcDept implements Serializable {

    private static final long serialVersionUID = 2114884834;

    private Integer   deptId;
    private String    simpleName;
    private String    fullName;
    private String    tips;
    private Integer   pDeptId;
    private String    status;
    private String    operator;
    private Timestamp updateTime;
    private Timestamp createTime;

    public TRcDept() {}

    public TRcDept(TRcDept value) {
        this.deptId = value.deptId;
        this.simpleName = value.simpleName;
        this.fullName = value.fullName;
        this.tips = value.tips;
        this.pDeptId = value.pDeptId;
        this.status = value.status;
        this.operator = value.operator;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public TRcDept(
        Integer   deptId,
        String    simpleName,
        String    fullName,
        String    tips,
        Integer   pDeptId,
        String    status,
        String    operator,
        Timestamp updateTime,
        Timestamp createTime
    ) {
        this.deptId = deptId;
        this.simpleName = simpleName;
        this.fullName = fullName;
        this.tips = tips;
        this.pDeptId = pDeptId;
        this.status = status;
        this.operator = operator;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public Integer getDeptId() {
        return this.deptId;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public String getSimpleName() {
        return this.simpleName;
    }

    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getTips() {
        return this.tips;
    }

    public void setTips(String tips) {
        this.tips = tips;
    }

    public Integer getPDeptId() {
        return this.pDeptId;
    }

    public void setPDeptId(Integer pDeptId) {
        this.pDeptId = pDeptId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getOperator() {
        return this.operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRcDept (");

        sb.append(deptId);
        sb.append(", ").append(simpleName);
        sb.append(", ").append(fullName);
        sb.append(", ").append(tips);
        sb.append(", ").append(pDeptId);
        sb.append(", ").append(status);
        sb.append(", ").append(operator);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
