/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcRole implements Serializable {

    private static final long serialVersionUID = 1955791509;

    private Integer   roleId;
    private String    name;
    private String    roleScope;
    private String    role;
    private String    tips;
    private String    status;
    private String    operator;
    private Timestamp updateTime;
    private Timestamp createTime;

    public TRcRole() {}

    public TRcRole(TRcRole value) {
        this.roleId = value.roleId;
        this.name = value.name;
        this.roleScope = value.roleScope;
        this.role = value.role;
        this.tips = value.tips;
        this.status = value.status;
        this.operator = value.operator;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public TRcRole(
        Integer   roleId,
        String    name,
        String    roleScope,
        String    role,
        String    tips,
        String    status,
        String    operator,
        Timestamp updateTime,
        Timestamp createTime
    ) {
        this.roleId = roleId;
        this.name = name;
        this.roleScope = roleScope;
        this.role = role;
        this.tips = tips;
        this.status = status;
        this.operator = operator;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRoleScope() {
        return this.roleScope;
    }

    public void setRoleScope(String roleScope) {
        this.roleScope = roleScope;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getTips() {
        return this.tips;
    }

    public void setTips(String tips) {
        this.tips = tips;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getOperator() {
        return this.operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRcRole (");

        sb.append(roleId);
        sb.append(", ").append(name);
        sb.append(", ").append(roleScope);
        sb.append(", ").append(role);
        sb.append(", ").append(tips);
        sb.append(", ").append(status);
        sb.append(", ").append(operator);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
