/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUser implements Serializable {

    private static final long serialVersionUID = -740474838;

    private Integer   userId;
    private String    avatar;
    private String    userName;
    private String    password;
    private String    salt;
    private String    fullName;
    private Timestamp birthday;
    private String    userScope;
    private String    sex;
    private String    email;
    private String    phone;
    private String    dingUserId;
    private String    wechatUserId;
    private String    corpNumber;
    private String    status;
    private String    operator;
    private Timestamp updateTime;
    private Timestamp createTime;

    public TRcUser() {}

    public TRcUser(TRcUser value) {
        this.userId = value.userId;
        this.avatar = value.avatar;
        this.userName = value.userName;
        this.password = value.password;
        this.salt = value.salt;
        this.fullName = value.fullName;
        this.birthday = value.birthday;
        this.userScope = value.userScope;
        this.sex = value.sex;
        this.email = value.email;
        this.phone = value.phone;
        this.dingUserId = value.dingUserId;
        this.wechatUserId = value.wechatUserId;
        this.corpNumber = value.corpNumber;
        this.status = value.status;
        this.operator = value.operator;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public TRcUser(
        Integer   userId,
        String    avatar,
        String    userName,
        String    password,
        String    salt,
        String    fullName,
        Timestamp birthday,
        String    userScope,
        String    sex,
        String    email,
        String    phone,
        String    dingUserId,
        String    wechatUserId,
        String    corpNumber,
        String    status,
        String    operator,
        Timestamp updateTime,
        Timestamp createTime
    ) {
        this.userId = userId;
        this.avatar = avatar;
        this.userName = userName;
        this.password = password;
        this.salt = salt;
        this.fullName = fullName;
        this.birthday = birthday;
        this.userScope = userScope;
        this.sex = sex;
        this.email = email;
        this.phone = phone;
        this.dingUserId = dingUserId;
        this.wechatUserId = wechatUserId;
        this.corpNumber = corpNumber;
        this.status = status;
        this.operator = operator;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Timestamp getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Timestamp birthday) {
        this.birthday = birthday;
    }

    public String getUserScope() {
        return this.userScope;
    }

    public void setUserScope(String userScope) {
        this.userScope = userScope;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getDingUserId() {
        return this.dingUserId;
    }

    public void setDingUserId(String dingUserId) {
        this.dingUserId = dingUserId;
    }

    public String getWechatUserId() {
        return this.wechatUserId;
    }

    public void setWechatUserId(String wechatUserId) {
        this.wechatUserId = wechatUserId;
    }

    public String getCorpNumber() {
        return this.corpNumber;
    }

    public void setCorpNumber(String corpNumber) {
        this.corpNumber = corpNumber;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getOperator() {
        return this.operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRcUser (");

        sb.append(userId);
        sb.append(", ").append(avatar);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(salt);
        sb.append(", ").append(fullName);
        sb.append(", ").append(birthday);
        sb.append(", ").append(userScope);
        sb.append(", ").append(sex);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(dingUserId);
        sb.append(", ").append(wechatUserId);
        sb.append(", ").append(corpNumber);
        sb.append(", ").append(status);
        sb.append(", ").append(operator);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
