/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserRole implements Serializable {

    private static final long serialVersionUID = -1167825324;

    private Integer   userRoleId;
    private Integer   userId;
    private Integer   roleId;
    private String    status;
    private String    operator;
    private Timestamp updateTime;
    private Timestamp createTime;

    public TRcUserRole() {}

    public TRcUserRole(TRcUserRole value) {
        this.userRoleId = value.userRoleId;
        this.userId = value.userId;
        this.roleId = value.roleId;
        this.status = value.status;
        this.operator = value.operator;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public TRcUserRole(
        Integer   userRoleId,
        Integer   userId,
        Integer   roleId,
        String    status,
        String    operator,
        Timestamp updateTime,
        Timestamp createTime
    ) {
        this.userRoleId = userRoleId;
        this.userId = userId;
        this.roleId = roleId;
        this.status = status;
        this.operator = operator;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public Integer getUserRoleId() {
        return this.userRoleId;
    }

    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getOperator() {
        return this.operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRcUserRole (");

        sb.append(userRoleId);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);
        sb.append(", ").append(status);
        sb.append(", ").append(operator);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
