/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.internal.async.AbstractAsyncVertxDAO;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcDept;
import org.cuber.upms.repo.tables.records.TRcDeptRecord;
import org.jooq.Configuration;


import io.reactivex.Completable;
import io.reactivex.Observable;
import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.async.AsyncRXQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcDeptDao extends AbstractAsyncVertxDAO<TRcDeptRecord, org.cuber.upms.repo.tables.pojos.TRcDept, Integer, Single<List<org.cuber.upms.repo.tables.pojos.TRcDept>>, Single<Optional<org.cuber.upms.repo.tables.pojos.TRcDept>>, Single<Integer>, Single<Integer>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<TRcDeptRecord,org.cuber.upms.repo.tables.pojos.TRcDept,Integer> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the MYSQL types or POSTGRES.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public TRcDeptDao(Configuration configuration,io.vertx.reactivex.ext.asyncsql.AsyncSQLClient delegate) {
        super(TRcDept.T_RC_DEPT, org.cuber.upms.repo.tables.pojos.TRcDept.class, new AsyncRXQueryExecutor<TRcDeptRecord,org.cuber.upms.repo.tables.pojos.TRcDept,Integer>(delegate,org.cuber.upms.repo.tables.pojos.TRcDept::new, TRcDept.T_RC_DEPT), configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.cuber.upms.repo.tables.pojos.TRcDept object) {
        return object.getDeptId();
    }

    /**
     * Find records that have <code>simple_name IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcDept>> findManyBySimpleName(List<String> values) {
        return findManyByCondition(TRcDept.T_RC_DEPT.SIMPLE_NAME.in(values));
    }

    /**
     * Find records that have <code>full_name IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcDept>> findManyByFullName(List<String> values) {
        return findManyByCondition(TRcDept.T_RC_DEPT.FULL_NAME.in(values));
    }

    /**
     * Find records that have <code>tips IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcDept>> findManyByTips(List<String> values) {
        return findManyByCondition(TRcDept.T_RC_DEPT.TIPS.in(values));
    }

    /**
     * Find records that have <code>p_dept_id IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcDept>> findManyByPDeptId(List<Integer> values) {
        return findManyByCondition(TRcDept.T_RC_DEPT.P_DEPT_ID.in(values));
    }

    /**
     * Find records that have <code>status IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcDept>> findManyByStatus(List<String> values) {
        return findManyByCondition(TRcDept.T_RC_DEPT.STATUS.in(values));
    }

    /**
     * Find records that have <code>operator IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcDept>> findManyByOperator(List<String> values) {
        return findManyByCondition(TRcDept.T_RC_DEPT.OPERATOR.in(values));
    }

    /**
     * Find records that have <code>update_time IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcDept>> findManyByUpdateTime(List<LocalDateTime> values) {
        return findManyByCondition(TRcDept.T_RC_DEPT.UPDATE_TIME.in(values));
    }

    /**
     * Find records that have <code>create_time IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcDept>> findManyByCreateTime(List<LocalDateTime> values) {
        return findManyByCondition(TRcDept.T_RC_DEPT.CREATE_TIME.in(values));
    }

    @Override
    protected java.util.function.Function<Object,Integer> keyConverter(){
        return lastId -> Integer.valueOf(((Long)lastId).intValue());
    }
}
