/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.internal.async.AbstractAsyncVertxDAO;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcUserRole;
import org.cuber.upms.repo.tables.records.TRcUserRoleRecord;
import org.jooq.Configuration;


import io.reactivex.Completable;
import io.reactivex.Observable;
import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.async.AsyncRXQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserRoleDao extends AbstractAsyncVertxDAO<TRcUserRoleRecord, org.cuber.upms.repo.tables.pojos.TRcUserRole, Integer, Single<List<org.cuber.upms.repo.tables.pojos.TRcUserRole>>, Single<Optional<org.cuber.upms.repo.tables.pojos.TRcUserRole>>, Single<Integer>, Single<Integer>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<TRcUserRoleRecord,org.cuber.upms.repo.tables.pojos.TRcUserRole,Integer> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the MYSQL types or POSTGRES.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public TRcUserRoleDao(Configuration configuration,io.vertx.reactivex.ext.asyncsql.AsyncSQLClient delegate) {
        super(TRcUserRole.T_RC_USER_ROLE, org.cuber.upms.repo.tables.pojos.TRcUserRole.class, new AsyncRXQueryExecutor<TRcUserRoleRecord,org.cuber.upms.repo.tables.pojos.TRcUserRole,Integer>(delegate,org.cuber.upms.repo.tables.pojos.TRcUserRole::new, TRcUserRole.T_RC_USER_ROLE), configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.cuber.upms.repo.tables.pojos.TRcUserRole object) {
        return object.getUserRoleId();
    }

    /**
     * Find records that have <code>user_id IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserRole>> findManyByUserId(List<Integer> values) {
        return findManyByCondition(TRcUserRole.T_RC_USER_ROLE.USER_ID.in(values));
    }

    /**
     * Find records that have <code>role_id IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserRole>> findManyByRoleId(List<Integer> values) {
        return findManyByCondition(TRcUserRole.T_RC_USER_ROLE.ROLE_ID.in(values));
    }

    /**
     * Find records that have <code>status IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserRole>> findManyByStatus(List<String> values) {
        return findManyByCondition(TRcUserRole.T_RC_USER_ROLE.STATUS.in(values));
    }

    /**
     * Find records that have <code>operator IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserRole>> findManyByOperator(List<String> values) {
        return findManyByCondition(TRcUserRole.T_RC_USER_ROLE.OPERATOR.in(values));
    }

    /**
     * Find records that have <code>update_time IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserRole>> findManyByUpdateTime(List<LocalDateTime> values) {
        return findManyByCondition(TRcUserRole.T_RC_USER_ROLE.UPDATE_TIME.in(values));
    }

    /**
     * Find records that have <code>create_time IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserRole>> findManyByCreateTime(List<LocalDateTime> values) {
        return findManyByCondition(TRcUserRole.T_RC_USER_ROLE.CREATE_TIME.in(values));
    }

    @Override
    protected java.util.function.Function<Object,Integer> keyConverter(){
        return lastId -> Integer.valueOf(((Long)lastId).intValue());
    }
}
