/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.internal.async.AbstractAsyncVertxDAO;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcUserDept;
import org.cuber.upms.repo.tables.records.TRcUserDeptRecord;
import org.jooq.Configuration;


import io.reactivex.Completable;
import io.reactivex.Observable;
import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.async.AsyncRXQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserDeptDao extends AbstractAsyncVertxDAO<TRcUserDeptRecord, org.cuber.upms.repo.tables.pojos.TRcUserDept, Integer, Single<List<org.cuber.upms.repo.tables.pojos.TRcUserDept>>, Single<Optional<org.cuber.upms.repo.tables.pojos.TRcUserDept>>, Single<Integer>, Single<Integer>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<TRcUserDeptRecord,org.cuber.upms.repo.tables.pojos.TRcUserDept,Integer> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the MYSQL types or POSTGRES.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public TRcUserDeptDao(Configuration configuration,io.vertx.reactivex.ext.asyncsql.AsyncSQLClient delegate) {
        super(TRcUserDept.T_RC_USER_DEPT, org.cuber.upms.repo.tables.pojos.TRcUserDept.class, new AsyncRXQueryExecutor<TRcUserDeptRecord,org.cuber.upms.repo.tables.pojos.TRcUserDept,Integer>(delegate,org.cuber.upms.repo.tables.pojos.TRcUserDept::new, TRcUserDept.T_RC_USER_DEPT), configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.cuber.upms.repo.tables.pojos.TRcUserDept object) {
        return object.getUserDeptId();
    }

    /**
     * Find records that have <code>user_id IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserDept>> findManyByUserId(List<Integer> values) {
        return findManyByCondition(TRcUserDept.T_RC_USER_DEPT.USER_ID.in(values));
    }

    /**
     * Find records that have <code>dept_id IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserDept>> findManyByDeptId(List<Integer> values) {
        return findManyByCondition(TRcUserDept.T_RC_USER_DEPT.DEPT_ID.in(values));
    }

    /**
     * Find records that have <code>status IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserDept>> findManyByStatus(List<String> values) {
        return findManyByCondition(TRcUserDept.T_RC_USER_DEPT.STATUS.in(values));
    }

    /**
     * Find records that have <code>operator IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserDept>> findManyByOperator(List<String> values) {
        return findManyByCondition(TRcUserDept.T_RC_USER_DEPT.OPERATOR.in(values));
    }

    /**
     * Find records that have <code>update_time IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserDept>> findManyByUpdateTime(List<LocalDateTime> values) {
        return findManyByCondition(TRcUserDept.T_RC_USER_DEPT.UPDATE_TIME.in(values));
    }

    /**
     * Find records that have <code>create_time IN (values)</code> asynchronously
     */
    public Single<List<org.cuber.upms.repo.tables.pojos.TRcUserDept>> findManyByCreateTime(List<LocalDateTime> values) {
        return findManyByCondition(TRcUserDept.T_RC_USER_DEPT.CREATE_TIME.in(values));
    }

    @Override
    protected java.util.function.Function<Object,Integer> keyConverter(){
        return lastId -> Integer.valueOf(((Long)lastId).intValue());
    }
}
