/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcUser;
import org.cuber.upms.repo.tables.records.TRcUserRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserDao extends DAOImpl<TRcUserRecord, org.cuber.upms.repo.tables.pojos.TRcUser, Integer> {

    /**
     * Create a new TRcUserDao without any configuration
     */
    public TRcUserDao() {
        super(TRcUser.T_RC_USER, org.cuber.upms.repo.tables.pojos.TRcUser.class);
    }

    /**
     * Create a new TRcUserDao with an attached configuration
     */
    public TRcUserDao(Configuration configuration) {
        super(TRcUser.T_RC_USER, org.cuber.upms.repo.tables.pojos.TRcUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.cuber.upms.repo.tables.pojos.TRcUser object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByUserId(Integer... values) {
        return fetch(TRcUser.T_RC_USER.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public org.cuber.upms.repo.tables.pojos.TRcUser fetchOneByUserId(Integer value) {
        return fetchOne(TRcUser.T_RC_USER.USER_ID, value);
    }

    /**
     * Fetch records that have <code>avatar IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByAvatar(String... values) {
        return fetch(TRcUser.T_RC_USER.AVATAR, values);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByUserName(String... values) {
        return fetch(TRcUser.T_RC_USER.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByPassword(String... values) {
        return fetch(TRcUser.T_RC_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>salt IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchBySalt(String... values) {
        return fetch(TRcUser.T_RC_USER.SALT, values);
    }

    /**
     * Fetch records that have <code>full_name IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByFullName(String... values) {
        return fetch(TRcUser.T_RC_USER.FULL_NAME, values);
    }

    /**
     * Fetch records that have <code>birthday IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByBirthday(Timestamp... values) {
        return fetch(TRcUser.T_RC_USER.BIRTHDAY, values);
    }

    /**
     * Fetch records that have <code>user_scope IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByUserScope(String... values) {
        return fetch(TRcUser.T_RC_USER.USER_SCOPE, values);
    }

    /**
     * Fetch records that have <code>sex IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchBySex(String... values) {
        return fetch(TRcUser.T_RC_USER.SEX, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByEmail(String... values) {
        return fetch(TRcUser.T_RC_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByPhone(String... values) {
        return fetch(TRcUser.T_RC_USER.PHONE, values);
    }

    /**
     * Fetch records that have <code>ding_user_id IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByDingUserId(String... values) {
        return fetch(TRcUser.T_RC_USER.DING_USER_ID, values);
    }

    /**
     * Fetch records that have <code>wechat_user_id IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByWechatUserId(String... values) {
        return fetch(TRcUser.T_RC_USER.WECHAT_USER_ID, values);
    }

    /**
     * Fetch records that have <code>corp_number IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByCorpNumber(String... values) {
        return fetch(TRcUser.T_RC_USER.CORP_NUMBER, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByStatus(String... values) {
        return fetch(TRcUser.T_RC_USER.STATUS, values);
    }

    /**
     * Fetch records that have <code>operator IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByOperator(String... values) {
        return fetch(TRcUser.T_RC_USER.OPERATOR, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByUpdateTime(Timestamp... values) {
        return fetch(TRcUser.T_RC_USER.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUser> fetchByCreateTime(Timestamp... values) {
        return fetch(TRcUser.T_RC_USER.CREATE_TIME, values);
    }
}
