/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcDept;
import org.cuber.upms.repo.tables.records.TRcDeptRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcDeptDao extends DAOImpl<TRcDeptRecord, org.cuber.upms.repo.tables.pojos.TRcDept, Integer> {

    /**
     * Create a new TRcDeptDao without any configuration
     */
    public TRcDeptDao() {
        super(TRcDept.T_RC_DEPT, org.cuber.upms.repo.tables.pojos.TRcDept.class);
    }

    /**
     * Create a new TRcDeptDao with an attached configuration
     */
    public TRcDeptDao(Configuration configuration) {
        super(TRcDept.T_RC_DEPT, org.cuber.upms.repo.tables.pojos.TRcDept.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.cuber.upms.repo.tables.pojos.TRcDept object) {
        return object.getDeptId();
    }

    /**
     * Fetch records that have <code>dept_id IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcDept> fetchByDeptId(Integer... values) {
        return fetch(TRcDept.T_RC_DEPT.DEPT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>dept_id = value</code>
     */
    public org.cuber.upms.repo.tables.pojos.TRcDept fetchOneByDeptId(Integer value) {
        return fetchOne(TRcDept.T_RC_DEPT.DEPT_ID, value);
    }

    /**
     * Fetch records that have <code>simple_name IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcDept> fetchBySimpleName(String... values) {
        return fetch(TRcDept.T_RC_DEPT.SIMPLE_NAME, values);
    }

    /**
     * Fetch records that have <code>full_name IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcDept> fetchByFullName(String... values) {
        return fetch(TRcDept.T_RC_DEPT.FULL_NAME, values);
    }

    /**
     * Fetch records that have <code>tips IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcDept> fetchByTips(String... values) {
        return fetch(TRcDept.T_RC_DEPT.TIPS, values);
    }

    /**
     * Fetch records that have <code>p_dept_id IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcDept> fetchByPDeptId(Integer... values) {
        return fetch(TRcDept.T_RC_DEPT.P_DEPT_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcDept> fetchByStatus(String... values) {
        return fetch(TRcDept.T_RC_DEPT.STATUS, values);
    }

    /**
     * Fetch records that have <code>operator IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcDept> fetchByOperator(String... values) {
        return fetch(TRcDept.T_RC_DEPT.OPERATOR, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcDept> fetchByUpdateTime(Timestamp... values) {
        return fetch(TRcDept.T_RC_DEPT.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcDept> fetchByCreateTime(Timestamp... values) {
        return fetch(TRcDept.T_RC_DEPT.CREATE_TIME, values);
    }
}
