/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcUserRole;
import org.cuber.upms.repo.tables.records.TRcUserRoleRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserRoleDao extends DAOImpl<TRcUserRoleRecord, org.cuber.upms.repo.tables.pojos.TRcUserRole, Integer> {

    /**
     * Create a new TRcUserRoleDao without any configuration
     */
    public TRcUserRoleDao() {
        super(TRcUserRole.T_RC_USER_ROLE, org.cuber.upms.repo.tables.pojos.TRcUserRole.class);
    }

    /**
     * Create a new TRcUserRoleDao with an attached configuration
     */
    public TRcUserRoleDao(Configuration configuration) {
        super(TRcUserRole.T_RC_USER_ROLE, org.cuber.upms.repo.tables.pojos.TRcUserRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.cuber.upms.repo.tables.pojos.TRcUserRole object) {
        return object.getUserRoleId();
    }

    /**
     * Fetch records that have <code>user_role_id IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUserRole> fetchByUserRoleId(Integer... values) {
        return fetch(TRcUserRole.T_RC_USER_ROLE.USER_ROLE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_role_id = value</code>
     */
    public org.cuber.upms.repo.tables.pojos.TRcUserRole fetchOneByUserRoleId(Integer value) {
        return fetchOne(TRcUserRole.T_RC_USER_ROLE.USER_ROLE_ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUserRole> fetchByUserId(Integer... values) {
        return fetch(TRcUserRole.T_RC_USER_ROLE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUserRole> fetchByRoleId(Integer... values) {
        return fetch(TRcUserRole.T_RC_USER_ROLE.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUserRole> fetchByStatus(String... values) {
        return fetch(TRcUserRole.T_RC_USER_ROLE.STATUS, values);
    }

    /**
     * Fetch records that have <code>operator IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUserRole> fetchByOperator(String... values) {
        return fetch(TRcUserRole.T_RC_USER_ROLE.OPERATOR, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUserRole> fetchByUpdateTime(Timestamp... values) {
        return fetch(TRcUserRole.T_RC_USER_ROLE.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<org.cuber.upms.repo.tables.pojos.TRcUserRole> fetchByCreateTime(Timestamp... values) {
        return fetch(TRcUserRole.T_RC_USER_ROLE.CREATE_TIME, values);
    }
}
