/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITRcRole extends VertxPojo, Serializable {

    /**
     * Setter for <code>upms.t_rc_role.role_id</code>. 主键
     */
    public ITRcRole setRoleId(Integer value);

    /**
     * Getter for <code>upms.t_rc_role.role_id</code>. 主键
     */
    public Integer getRoleId();

    /**
     * Setter for <code>upms.t_rc_role.name</code>. 角色中文
     */
    public ITRcRole setName(String value);

    /**
     * Getter for <code>upms.t_rc_role.name</code>. 角色中文
     */
    public String getName();

    /**
     * Setter for <code>upms.t_rc_role.role_scope</code>. 角色系统
     */
    public ITRcRole setRoleScope(String value);

    /**
     * Getter for <code>upms.t_rc_role.role_scope</code>. 角色系统
     */
    public String getRoleScope();

    /**
     * Setter for <code>upms.t_rc_role.role</code>. 角色实际CODE
     */
    public ITRcRole setRole(String value);

    /**
     * Getter for <code>upms.t_rc_role.role</code>. 角色实际CODE
     */
    public String getRole();

    /**
     * Setter for <code>upms.t_rc_role.tips</code>. 角色描述
     */
    public ITRcRole setTips(String value);

    /**
     * Getter for <code>upms.t_rc_role.tips</code>. 角色描述
     */
    public String getTips();

    /**
     * Setter for <code>upms.t_rc_role.status</code>. 是否有效,0/1 无效/有效
     */
    public ITRcRole setStatus(String value);

    /**
     * Getter for <code>upms.t_rc_role.status</code>. 是否有效,0/1 无效/有效
     */
    public String getStatus();

    /**
     * Setter for <code>upms.t_rc_role.operator</code>.
     */
    public ITRcRole setOperator(String value);

    /**
     * Getter for <code>upms.t_rc_role.operator</code>.
     */
    public String getOperator();

    /**
     * Setter for <code>upms.t_rc_role.update_time</code>.
     */
    public ITRcRole setUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>upms.t_rc_role.update_time</code>.
     */
    public LocalDateTime getUpdateTime();

    /**
     * Setter for <code>upms.t_rc_role.create_time</code>.
     */
    public ITRcRole setCreateTime(LocalDateTime value);

    /**
     * Getter for <code>upms.t_rc_role.create_time</code>.
     */
    public LocalDateTime getCreateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITRcRole
     */
    public void from(org.cuber.upms.repo.tables.interfaces.ITRcRole from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITRcRole
     */
    public <E extends org.cuber.upms.repo.tables.interfaces.ITRcRole> E into(E into);

    @Override
    public default ITRcRole fromJson(io.vertx.core.json.JsonObject json) {
        setRoleId(json.getInteger("role_id"));
        setName(json.getString("name"));
        setRoleScope(json.getString("role_scope"));
        setRole(json.getString("role"));
        setTips(json.getString("tips"));
        setStatus(json.getString("status"));
        setOperator(json.getString("operator"));
        // Omitting unrecognized type java.time.LocalDateTime for column update_time!
        // Omitting unrecognized type java.time.LocalDateTime for column create_time!
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("role_id",getRoleId());
        json.put("name",getName());
        json.put("role_scope",getRoleScope());
        json.put("role",getRole());
        json.put("tips",getTips());
        json.put("status",getStatus());
        json.put("operator",getOperator());
        // Omitting unrecognized type java.time.LocalDateTime for column update_time!
        // Omitting unrecognized type java.time.LocalDateTime for column create_time!
        return json;
    }

}
