/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITRcMenu extends VertxPojo, Serializable {

    /**
     * Setter for <code>upms.t_rc_menu.menu_id</code>.
     */
    public ITRcMenu setMenuId(Integer value);

    /**
     * Getter for <code>upms.t_rc_menu.menu_id</code>.
     */
    public Integer getMenuId();

    /**
     * Setter for <code>upms.t_rc_menu.code</code>. 菜单code
     */
    public ITRcMenu setCode(String value);

    /**
     * Getter for <code>upms.t_rc_menu.code</code>. 菜单code
     */
    public String getCode();

    /**
     * Setter for <code>upms.t_rc_menu.p_code</code>. 父菜单code
     */
    public ITRcMenu setPCode(String value);

    /**
     * Getter for <code>upms.t_rc_menu.p_code</code>. 父菜单code
     */
    public String getPCode();

    /**
     * Setter for <code>upms.t_rc_menu.name</code>. 菜单名
     */
    public ITRcMenu setName(String value);

    /**
     * Getter for <code>upms.t_rc_menu.name</code>. 菜单名
     */
    public String getName();

    /**
     * Setter for <code>upms.t_rc_menu.url</code>. 菜单地址
     */
    public ITRcMenu setUrl(String value);

    /**
     * Getter for <code>upms.t_rc_menu.url</code>. 菜单地址
     */
    public String getUrl();

    /**
     * Setter for <code>upms.t_rc_menu.menu_type</code>. 菜单类型 1.菜单,2.按钮
     */
    public ITRcMenu setMenuType(String value);

    /**
     * Getter for <code>upms.t_rc_menu.menu_type</code>. 菜单类型 1.菜单,2.按钮
     */
    public String getMenuType();

    /**
     * Setter for <code>upms.t_rc_menu.menu_scope</code>. 菜单属性
     */
    public ITRcMenu setMenuScope(String value);

    /**
     * Getter for <code>upms.t_rc_menu.menu_scope</code>. 菜单属性
     */
    public String getMenuScope();

    /**
     * Setter for <code>upms.t_rc_menu.level</code>. 菜单等级
     */
    public ITRcMenu setLevel(Integer value);

    /**
     * Getter for <code>upms.t_rc_menu.level</code>. 菜单等级
     */
    public Integer getLevel();

    /**
     * Setter for <code>upms.t_rc_menu.sort</code>. 菜单排序
     */
    public ITRcMenu setSort(Integer value);

    /**
     * Getter for <code>upms.t_rc_menu.sort</code>. 菜单排序
     */
    public Integer getSort();

    /**
     * Setter for <code>upms.t_rc_menu.status</code>.
     */
    public ITRcMenu setStatus(String value);

    /**
     * Getter for <code>upms.t_rc_menu.status</code>.
     */
    public String getStatus();

    /**
     * Setter for <code>upms.t_rc_menu.operator</code>.
     */
    public ITRcMenu setOperator(String value);

    /**
     * Getter for <code>upms.t_rc_menu.operator</code>.
     */
    public String getOperator();

    /**
     * Setter for <code>upms.t_rc_menu.update_time</code>.
     */
    public ITRcMenu setUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>upms.t_rc_menu.update_time</code>.
     */
    public LocalDateTime getUpdateTime();

    /**
     * Setter for <code>upms.t_rc_menu.create_time</code>.
     */
    public ITRcMenu setCreateTime(LocalDateTime value);

    /**
     * Getter for <code>upms.t_rc_menu.create_time</code>.
     */
    public LocalDateTime getCreateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITRcMenu
     */
    public void from(org.cuber.upms.repo.tables.interfaces.ITRcMenu from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITRcMenu
     */
    public <E extends org.cuber.upms.repo.tables.interfaces.ITRcMenu> E into(E into);

    @Override
    public default ITRcMenu fromJson(io.vertx.core.json.JsonObject json) {
        setMenuId(json.getInteger("menu_id"));
        setCode(json.getString("code"));
        setPCode(json.getString("p_code"));
        setName(json.getString("name"));
        setUrl(json.getString("url"));
        setMenuType(json.getString("menu_type"));
        setMenuScope(json.getString("menu_scope"));
        setLevel(json.getInteger("level"));
        setSort(json.getInteger("sort"));
        setStatus(json.getString("status"));
        setOperator(json.getString("operator"));
        // Omitting unrecognized type java.time.LocalDateTime for column update_time!
        // Omitting unrecognized type java.time.LocalDateTime for column create_time!
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("menu_id",getMenuId());
        json.put("code",getCode());
        json.put("p_code",getPCode());
        json.put("name",getName());
        json.put("url",getUrl());
        json.put("menu_type",getMenuType());
        json.put("menu_scope",getMenuScope());
        json.put("level",getLevel());
        json.put("sort",getSort());
        json.put("status",getStatus());
        json.put("operator",getOperator());
        // Omitting unrecognized type java.time.LocalDateTime for column update_time!
        // Omitting unrecognized type java.time.LocalDateTime for column create_time!
        return json;
    }

}
