/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITRcUserDept extends VertxPojo, Serializable {

    /**
     * Setter for <code>upms.t_rc_user_dept.user_dept_id</code>.
     */
    public ITRcUserDept setUserDeptId(Integer value);

    /**
     * Getter for <code>upms.t_rc_user_dept.user_dept_id</code>.
     */
    public Integer getUserDeptId();

    /**
     * Setter for <code>upms.t_rc_user_dept.user_id</code>.
     */
    public ITRcUserDept setUserId(Integer value);

    /**
     * Getter for <code>upms.t_rc_user_dept.user_id</code>.
     */
    public Integer getUserId();

    /**
     * Setter for <code>upms.t_rc_user_dept.dept_id</code>.
     */
    public ITRcUserDept setDeptId(Integer value);

    /**
     * Getter for <code>upms.t_rc_user_dept.dept_id</code>.
     */
    public Integer getDeptId();

    /**
     * Setter for <code>upms.t_rc_user_dept.status</code>.
     */
    public ITRcUserDept setStatus(String value);

    /**
     * Getter for <code>upms.t_rc_user_dept.status</code>.
     */
    public String getStatus();

    /**
     * Setter for <code>upms.t_rc_user_dept.operator</code>.
     */
    public ITRcUserDept setOperator(String value);

    /**
     * Getter for <code>upms.t_rc_user_dept.operator</code>.
     */
    public String getOperator();

    /**
     * Setter for <code>upms.t_rc_user_dept.update_time</code>.
     */
    public ITRcUserDept setUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>upms.t_rc_user_dept.update_time</code>.
     */
    public LocalDateTime getUpdateTime();

    /**
     * Setter for <code>upms.t_rc_user_dept.create_time</code>.
     */
    public ITRcUserDept setCreateTime(LocalDateTime value);

    /**
     * Getter for <code>upms.t_rc_user_dept.create_time</code>.
     */
    public LocalDateTime getCreateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITRcUserDept
     */
    public void from(org.cuber.upms.repo.tables.interfaces.ITRcUserDept from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITRcUserDept
     */
    public <E extends org.cuber.upms.repo.tables.interfaces.ITRcUserDept> E into(E into);

    @Override
    public default ITRcUserDept fromJson(io.vertx.core.json.JsonObject json) {
        setUserDeptId(json.getInteger("user_dept_id"));
        setUserId(json.getInteger("user_id"));
        setDeptId(json.getInteger("dept_id"));
        setStatus(json.getString("status"));
        setOperator(json.getString("operator"));
        // Omitting unrecognized type java.time.LocalDateTime for column update_time!
        // Omitting unrecognized type java.time.LocalDateTime for column create_time!
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("user_dept_id",getUserDeptId());
        json.put("user_id",getUserId());
        json.put("dept_id",getDeptId());
        json.put("status",getStatus());
        json.put("operator",getOperator());
        // Omitting unrecognized type java.time.LocalDateTime for column update_time!
        // Omitting unrecognized type java.time.LocalDateTime for column create_time!
        return json;
    }

}
