/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo;


import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Upms extends SchemaImpl {

    private static final long serialVersionUID = 715146116;

    /**
     * The reference instance of <code>upms</code>
     */
    public static final Upms UPMS = new Upms();

    /**
     * No further instances allowed
     */
    private Upms() {
        super("upms", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
}
