/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.Indexes;
import org.cuber.upms.repo.Keys;
import org.cuber.upms.repo.Upms;
import org.cuber.upms.repo.tables.records.TRcRoleRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcRole extends TableImpl<TRcRoleRecord> {

    private static final long serialVersionUID = 1435689243;

    /**
     * The reference instance of <code>upms.t_rc_role</code>
     */
    public static final TRcRole T_RC_ROLE = new TRcRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRcRoleRecord> getRecordType() {
        return TRcRoleRecord.class;
    }

    /**
     * The column <code>upms.t_rc_role.role_id</code>. 主键
     */
    public final TableField<TRcRoleRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('t_rc_role_role_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "主键");

    /**
     * The column <code>upms.t_rc_role.name</code>. 角色中文
     */
    public final TableField<TRcRoleRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "角色中文");

    /**
     * The column <code>upms.t_rc_role.role_scope</code>. 角色系统
     */
    public final TableField<TRcRoleRecord, String> ROLE_SCOPE = createField("role_scope", org.jooq.impl.SQLDataType.VARCHAR(64), this, "角色系统");

    /**
     * The column <code>upms.t_rc_role.role</code>. 角色实际CODE
     */
    public final TableField<TRcRoleRecord, String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "角色实际CODE");

    /**
     * The column <code>upms.t_rc_role.tips</code>. 角色描述
     */
    public final TableField<TRcRoleRecord, String> TIPS = createField("tips", org.jooq.impl.SQLDataType.VARCHAR(1024), this, "角色描述");

    /**
     * The column <code>upms.t_rc_role.status</code>. 是否有效,0/1 无效/有效
     */
    public final TableField<TRcRoleRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(2), this, "是否有效,0/1 无效/有效");

    /**
     * The column <code>upms.t_rc_role.operator</code>.
     */
    public final TableField<TRcRoleRecord, String> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>upms.t_rc_role.update_time</code>.
     */
    public final TableField<TRcRoleRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>upms.t_rc_role.create_time</code>.
     */
    public final TableField<TRcRoleRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>upms.t_rc_role</code> table reference
     */
    public TRcRole() {
        this(DSL.name("t_rc_role"), null);
    }

    /**
     * Create an aliased <code>upms.t_rc_role</code> table reference
     */
    public TRcRole(String alias) {
        this(DSL.name(alias), T_RC_ROLE);
    }

    /**
     * Create an aliased <code>upms.t_rc_role</code> table reference
     */
    public TRcRole(Name alias) {
        this(alias, T_RC_ROLE);
    }

    private TRcRole(Name alias, Table<TRcRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRcRole(Name alias, Table<TRcRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Upms.UPMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_UNQ_RC_ROLE_NAME, Indexes.IDX_UNQ_RC_ROLE_ROLE, Indexes.T_RC_ROLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TRcRoleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_RC_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TRcRoleRecord> getPrimaryKey() {
        return Keys.T_RC_ROLE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TRcRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<TRcRoleRecord>>asList(Keys.T_RC_ROLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRole as(String alias) {
        return new TRcRole(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRole as(Name alias) {
        return new TRcRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcRole rename(String name) {
        return new TRcRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcRole rename(Name name) {
        return new TRcRole(name, null);
    }
}
