/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.Indexes;
import org.cuber.upms.repo.Keys;
import org.cuber.upms.repo.Upms;
import org.cuber.upms.repo.tables.records.TRcRoleMenuRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcRoleMenu extends TableImpl<TRcRoleMenuRecord> {

    private static final long serialVersionUID = -1873360421;

    /**
     * The reference instance of <code>upms.t_rc_role_menu</code>
     */
    public static final TRcRoleMenu T_RC_ROLE_MENU = new TRcRoleMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRcRoleMenuRecord> getRecordType() {
        return TRcRoleMenuRecord.class;
    }

    /**
     * The column <code>upms.t_rc_role_menu.role_menu_id</code>.
     */
    public final TableField<TRcRoleMenuRecord, Integer> ROLE_MENU_ID = createField("role_menu_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('t_rc_role_menu_role_menu_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>upms.t_rc_role_menu.role_id</code>.
     */
    public final TableField<TRcRoleMenuRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>upms.t_rc_role_menu.menu_id</code>.
     */
    public final TableField<TRcRoleMenuRecord, Integer> MENU_ID = createField("menu_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>upms.t_rc_role_menu.status</code>.
     */
    public final TableField<TRcRoleMenuRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>upms.t_rc_role_menu.operator</code>.
     */
    public final TableField<TRcRoleMenuRecord, String> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>upms.t_rc_role_menu.update_time</code>.
     */
    public final TableField<TRcRoleMenuRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>upms.t_rc_role_menu.create_time</code>.
     */
    public final TableField<TRcRoleMenuRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>upms.t_rc_role_menu</code> table reference
     */
    public TRcRoleMenu() {
        this(DSL.name("t_rc_role_menu"), null);
    }

    /**
     * Create an aliased <code>upms.t_rc_role_menu</code> table reference
     */
    public TRcRoleMenu(String alias) {
        this(DSL.name(alias), T_RC_ROLE_MENU);
    }

    /**
     * Create an aliased <code>upms.t_rc_role_menu</code> table reference
     */
    public TRcRoleMenu(Name alias) {
        this(alias, T_RC_ROLE_MENU);
    }

    private TRcRoleMenu(Name alias, Table<TRcRoleMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRcRoleMenu(Name alias, Table<TRcRoleMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Upms.UPMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_RC_ROLE_MENU_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TRcRoleMenuRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_RC_ROLE_MENU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TRcRoleMenuRecord> getPrimaryKey() {
        return Keys.T_RC_ROLE_MENU_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TRcRoleMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<TRcRoleMenuRecord>>asList(Keys.T_RC_ROLE_MENU_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenu as(String alias) {
        return new TRcRoleMenu(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenu as(Name alias) {
        return new TRcRoleMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcRoleMenu rename(String name) {
        return new TRcRoleMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcRoleMenu rename(Name name) {
        return new TRcRoleMenu(name, null);
    }
}
