/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.Indexes;
import org.cuber.upms.repo.Keys;
import org.cuber.upms.repo.Upms;
import org.cuber.upms.repo.tables.records.TRcUserDeptRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserDept extends TableImpl<TRcUserDeptRecord> {

    private static final long serialVersionUID = 1648799328;

    /**
     * The reference instance of <code>upms.t_rc_user_dept</code>
     */
    public static final TRcUserDept T_RC_USER_DEPT = new TRcUserDept();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRcUserDeptRecord> getRecordType() {
        return TRcUserDeptRecord.class;
    }

    /**
     * The column <code>upms.t_rc_user_dept.user_dept_id</code>.
     */
    public final TableField<TRcUserDeptRecord, Integer> USER_DEPT_ID = createField("user_dept_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('t_rc_user_dept_user_dept_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>upms.t_rc_user_dept.user_id</code>.
     */
    public final TableField<TRcUserDeptRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>upms.t_rc_user_dept.dept_id</code>.
     */
    public final TableField<TRcUserDeptRecord, Integer> DEPT_ID = createField("dept_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>upms.t_rc_user_dept.status</code>.
     */
    public final TableField<TRcUserDeptRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>upms.t_rc_user_dept.operator</code>.
     */
    public final TableField<TRcUserDeptRecord, String> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>upms.t_rc_user_dept.update_time</code>.
     */
    public final TableField<TRcUserDeptRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>upms.t_rc_user_dept.create_time</code>.
     */
    public final TableField<TRcUserDeptRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>upms.t_rc_user_dept</code> table reference
     */
    public TRcUserDept() {
        this(DSL.name("t_rc_user_dept"), null);
    }

    /**
     * Create an aliased <code>upms.t_rc_user_dept</code> table reference
     */
    public TRcUserDept(String alias) {
        this(DSL.name(alias), T_RC_USER_DEPT);
    }

    /**
     * Create an aliased <code>upms.t_rc_user_dept</code> table reference
     */
    public TRcUserDept(Name alias) {
        this(alias, T_RC_USER_DEPT);
    }

    private TRcUserDept(Name alias, Table<TRcUserDeptRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRcUserDept(Name alias, Table<TRcUserDeptRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Upms.UPMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_RC_USER_DEPT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TRcUserDeptRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_RC_USER_DEPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TRcUserDeptRecord> getPrimaryKey() {
        return Keys.T_RC_USER_DEPT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TRcUserDeptRecord>> getKeys() {
        return Arrays.<UniqueKey<TRcUserDeptRecord>>asList(Keys.T_RC_USER_DEPT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDept as(String alias) {
        return new TRcUserDept(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDept as(Name alias) {
        return new TRcUserDept(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcUserDept rename(String name) {
        return new TRcUserDept(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcUserDept rename(Name name) {
        return new TRcUserDept(name, null);
    }
}
