/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.Indexes;
import org.cuber.upms.repo.Keys;
import org.cuber.upms.repo.Upms;
import org.cuber.upms.repo.tables.records.TRcUserRoleRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserRole extends TableImpl<TRcUserRoleRecord> {

    private static final long serialVersionUID = 122752815;

    /**
     * The reference instance of <code>upms.t_rc_user_role</code>
     */
    public static final TRcUserRole T_RC_USER_ROLE = new TRcUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRcUserRoleRecord> getRecordType() {
        return TRcUserRoleRecord.class;
    }

    /**
     * The column <code>upms.t_rc_user_role.user_role_id</code>.
     */
    public final TableField<TRcUserRoleRecord, Integer> USER_ROLE_ID = createField("user_role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('t_rc_user_role_user_role_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>upms.t_rc_user_role.user_id</code>.
     */
    public final TableField<TRcUserRoleRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>upms.t_rc_user_role.role_id</code>.
     */
    public final TableField<TRcUserRoleRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>upms.t_rc_user_role.status</code>.
     */
    public final TableField<TRcUserRoleRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>upms.t_rc_user_role.operator</code>.
     */
    public final TableField<TRcUserRoleRecord, String> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>upms.t_rc_user_role.update_time</code>.
     */
    public final TableField<TRcUserRoleRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>upms.t_rc_user_role.create_time</code>.
     */
    public final TableField<TRcUserRoleRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>upms.t_rc_user_role</code> table reference
     */
    public TRcUserRole() {
        this(DSL.name("t_rc_user_role"), null);
    }

    /**
     * Create an aliased <code>upms.t_rc_user_role</code> table reference
     */
    public TRcUserRole(String alias) {
        this(DSL.name(alias), T_RC_USER_ROLE);
    }

    /**
     * Create an aliased <code>upms.t_rc_user_role</code> table reference
     */
    public TRcUserRole(Name alias) {
        this(alias, T_RC_USER_ROLE);
    }

    private TRcUserRole(Name alias, Table<TRcUserRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRcUserRole(Name alias, Table<TRcUserRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Upms.UPMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_RC_USER_ROLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TRcUserRoleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_RC_USER_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TRcUserRoleRecord> getPrimaryKey() {
        return Keys.T_RC_USER_ROLE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TRcUserRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<TRcUserRoleRecord>>asList(Keys.T_RC_USER_ROLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRole as(String alias) {
        return new TRcUserRole(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRole as(Name alias) {
        return new TRcUserRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcUserRole rename(String name) {
        return new TRcUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcUserRole rename(Name name) {
        return new TRcUserRole(name, null);
    }
}
