spring:
  application:
    name: upms
  datasource:
    hikari:
      connection-init-sql: select 1
      connection-timeout: 5000
      idle-timeout: 300000
      minimum-idle: 5
    name: upms
    password: upms
    url: jdbc:postgresql://localhost:5432/upms
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: upms
zookeeper:
  hosts: 01.132.113.199:2181,101.132.113.199:2182,101.132.113.199:2183
