spring:
  application:
    name: upms
  datasource:
    hikari:
      connection-init-sql: select 1
      connection-timeout: 5000
      idle-timeout: 300000
      minimum-idle: 5
    name: upms
    password: upms
    url: jdbc:postgresql://localhost:5432/upms
    driver-class-name: org.postgresql.Driver
    username: upms
zookeeper:
  hosts: 101.132.113.199:2181,101.132.113.199:2182,101.132.113.199:2183

vertx:
  postgresql:
    host: 127.0.0.1
    port: 5432
    maxPoolSize: 20
    username: upms
    password: upms
jooq:
  dao:
    package: org.cuber.upms.repo.tables.daos
