/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcDept;
import org.cuber.upms.repo.tables.interfaces.ITRcDept;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcDeptRecord extends UpdatableRecordImpl<TRcDeptRecord> implements VertxPojo, Record9<Integer, String, String, String, Integer, String, String, LocalDateTime, LocalDateTime>, ITRcDept {

    private static final long serialVersionUID = -1706234681;

    /**
     * Setter for <code>upms.t_rc_dept.dept_id</code>.
     */
    @Override
    public TRcDeptRecord setDeptId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_dept.dept_id</code>.
     */
    @Override
    public Integer getDeptId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>upms.t_rc_dept.simple_name</code>. 部门简称
     */
    @Override
    public TRcDeptRecord setSimpleName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_dept.simple_name</code>. 部门简称
     */
    @Override
    public String getSimpleName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>upms.t_rc_dept.full_name</code>. 部门全称
     */
    @Override
    public TRcDeptRecord setFullName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_dept.full_name</code>. 部门全称
     */
    @Override
    public String getFullName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>upms.t_rc_dept.tips</code>.
     */
    @Override
    public TRcDeptRecord setTips(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_dept.tips</code>.
     */
    @Override
    public String getTips() {
        return (String) get(3);
    }

    /**
     * Setter for <code>upms.t_rc_dept.p_dept_id</code>. 父部门ID
     */
    @Override
    public TRcDeptRecord setPDeptId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_dept.p_dept_id</code>. 父部门ID
     */
    @Override
    public Integer getPDeptId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>upms.t_rc_dept.status</code>.
     */
    @Override
    public TRcDeptRecord setStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_dept.status</code>.
     */
    @Override
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>upms.t_rc_dept.operator</code>.
     */
    @Override
    public TRcDeptRecord setOperator(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_dept.operator</code>.
     */
    @Override
    public String getOperator() {
        return (String) get(6);
    }

    /**
     * Setter for <code>upms.t_rc_dept.update_time</code>.
     */
    @Override
    public TRcDeptRecord setUpdateTime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_dept.update_time</code>.
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>upms.t_rc_dept.create_time</code>.
     */
    @Override
    public TRcDeptRecord setCreateTime(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_dept.create_time</code>.
     */
    @Override
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRcDept.T_RC_DEPT.DEPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TRcDept.T_RC_DEPT.SIMPLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TRcDept.T_RC_DEPT.FULL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRcDept.T_RC_DEPT.TIPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TRcDept.T_RC_DEPT.P_DEPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TRcDept.T_RC_DEPT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TRcDept.T_RC_DEPT.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return TRcDept.T_RC_DEPT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return TRcDept.T_RC_DEPT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSimpleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTips();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getPDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSimpleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTips();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord value1(Integer value) {
        setDeptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord value2(String value) {
        setSimpleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord value3(String value) {
        setFullName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord value4(String value) {
        setTips(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord value5(Integer value) {
        setPDeptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord value7(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord value8(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcDeptRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6, String value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITRcDept from) {
        setDeptId(from.getDeptId());
        setSimpleName(from.getSimpleName());
        setFullName(from.getFullName());
        setTips(from.getTips());
        setPDeptId(from.getPDeptId());
        setStatus(from.getStatus());
        setOperator(from.getOperator());
        setUpdateTime(from.getUpdateTime());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITRcDept> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcDeptRecord
     */
    public TRcDeptRecord() {
        super(TRcDept.T_RC_DEPT);
    }

    /**
     * Create a detached, initialised TRcDeptRecord
     */
    public TRcDeptRecord(Integer deptId, String simpleName, String fullName, String tips, Integer pDeptId, String status, String operator, LocalDateTime updateTime, LocalDateTime createTime) {
        super(TRcDept.T_RC_DEPT);

        set(0, deptId);
        set(1, simpleName);
        set(2, fullName);
        set(3, tips);
        set(4, pDeptId);
        set(5, status);
        set(6, operator);
        set(7, updateTime);
        set(8, createTime);
    }

    public TRcDeptRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
