/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcMenu;
import org.cuber.upms.repo.tables.interfaces.ITRcMenu;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcMenuRecord extends UpdatableRecordImpl<TRcMenuRecord> implements VertxPojo, Record13<Integer, String, String, String, String, String, String, Integer, Integer, String, String, LocalDateTime, LocalDateTime>, ITRcMenu {

    private static final long serialVersionUID = 1597520853;

    /**
     * Setter for <code>upms.t_rc_menu.menu_id</code>.
     */
    @Override
    public TRcMenuRecord setMenuId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.menu_id</code>.
     */
    @Override
    public Integer getMenuId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>upms.t_rc_menu.code</code>. 菜单code
     */
    @Override
    public TRcMenuRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.code</code>. 菜单code
     */
    @Override
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>upms.t_rc_menu.p_code</code>. 父菜单code
     */
    @Override
    public TRcMenuRecord setPCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.p_code</code>. 父菜单code
     */
    @Override
    public String getPCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>upms.t_rc_menu.name</code>. 菜单名
     */
    @Override
    public TRcMenuRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.name</code>. 菜单名
     */
    @Override
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>upms.t_rc_menu.url</code>. 菜单地址
     */
    @Override
    public TRcMenuRecord setUrl(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.url</code>. 菜单地址
     */
    @Override
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>upms.t_rc_menu.menu_type</code>. 菜单类型 1.菜单,2.按钮
     */
    @Override
    public TRcMenuRecord setMenuType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.menu_type</code>. 菜单类型 1.菜单,2.按钮
     */
    @Override
    public String getMenuType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>upms.t_rc_menu.menu_scope</code>. 菜单属性
     */
    @Override
    public TRcMenuRecord setMenuScope(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.menu_scope</code>. 菜单属性
     */
    @Override
    public String getMenuScope() {
        return (String) get(6);
    }

    /**
     * Setter for <code>upms.t_rc_menu.level</code>. 菜单等级
     */
    @Override
    public TRcMenuRecord setLevel(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.level</code>. 菜单等级
     */
    @Override
    public Integer getLevel() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>upms.t_rc_menu.sort</code>. 菜单排序
     */
    @Override
    public TRcMenuRecord setSort(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.sort</code>. 菜单排序
     */
    @Override
    public Integer getSort() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>upms.t_rc_menu.status</code>.
     */
    @Override
    public TRcMenuRecord setStatus(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.status</code>.
     */
    @Override
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>upms.t_rc_menu.operator</code>.
     */
    @Override
    public TRcMenuRecord setOperator(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.operator</code>.
     */
    @Override
    public String getOperator() {
        return (String) get(10);
    }

    /**
     * Setter for <code>upms.t_rc_menu.update_time</code>.
     */
    @Override
    public TRcMenuRecord setUpdateTime(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.update_time</code>.
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>upms.t_rc_menu.create_time</code>.
     */
    @Override
    public TRcMenuRecord setCreateTime(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_menu.create_time</code>.
     */
    @Override
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, Integer, Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, Integer, Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRcMenu.T_RC_MENU.MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TRcMenu.T_RC_MENU.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TRcMenu.T_RC_MENU.P_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRcMenu.T_RC_MENU.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TRcMenu.T_RC_MENU.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TRcMenu.T_RC_MENU.MENU_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TRcMenu.T_RC_MENU.MENU_SCOPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TRcMenu.T_RC_MENU.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TRcMenu.T_RC_MENU.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TRcMenu.T_RC_MENU.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TRcMenu.T_RC_MENU.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return TRcMenu.T_RC_MENU.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return TRcMenu.T_RC_MENU.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMenuType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getMenuScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component13() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMenuType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMenuScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value1(Integer value) {
        setMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value3(String value) {
        setPCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value5(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value6(String value) {
        setMenuType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value7(String value) {
        setMenuScope(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value8(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value9(Integer value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value10(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value11(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value12(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord value13(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcMenuRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, Integer value9, String value10, String value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITRcMenu from) {
        setMenuId(from.getMenuId());
        setCode(from.getCode());
        setPCode(from.getPCode());
        setName(from.getName());
        setUrl(from.getUrl());
        setMenuType(from.getMenuType());
        setMenuScope(from.getMenuScope());
        setLevel(from.getLevel());
        setSort(from.getSort());
        setStatus(from.getStatus());
        setOperator(from.getOperator());
        setUpdateTime(from.getUpdateTime());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITRcMenu> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcMenuRecord
     */
    public TRcMenuRecord() {
        super(TRcMenu.T_RC_MENU);
    }

    /**
     * Create a detached, initialised TRcMenuRecord
     */
    public TRcMenuRecord(Integer menuId, String code, String pCode, String name, String url, String menuType, String menuScope, Integer level, Integer sort, String status, String operator, LocalDateTime updateTime, LocalDateTime createTime) {
        super(TRcMenu.T_RC_MENU);

        set(0, menuId);
        set(1, code);
        set(2, pCode);
        set(3, name);
        set(4, url);
        set(5, menuType);
        set(6, menuScope);
        set(7, level);
        set(8, sort);
        set(9, status);
        set(10, operator);
        set(11, updateTime);
        set(12, createTime);
    }

    public TRcMenuRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
