/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcRoleMenu;
import org.cuber.upms.repo.tables.interfaces.ITRcRoleMenu;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcRoleMenuRecord extends UpdatableRecordImpl<TRcRoleMenuRecord> implements VertxPojo, Record7<Integer, Integer, Integer, String, String, LocalDateTime, LocalDateTime>, ITRcRoleMenu {

    private static final long serialVersionUID = -483300443;

    /**
     * Setter for <code>upms.t_rc_role_menu.role_menu_id</code>.
     */
    @Override
    public TRcRoleMenuRecord setRoleMenuId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.role_menu_id</code>.
     */
    @Override
    public Integer getRoleMenuId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.role_id</code>.
     */
    @Override
    public TRcRoleMenuRecord setRoleId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.role_id</code>.
     */
    @Override
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.menu_id</code>.
     */
    @Override
    public TRcRoleMenuRecord setMenuId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.menu_id</code>.
     */
    @Override
    public Integer getMenuId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.status</code>.
     */
    @Override
    public TRcRoleMenuRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.status</code>.
     */
    @Override
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.operator</code>.
     */
    @Override
    public TRcRoleMenuRecord setOperator(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.operator</code>.
     */
    @Override
    public String getOperator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.update_time</code>.
     */
    @Override
    public TRcRoleMenuRecord setUpdateTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.update_time</code>.
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.create_time</code>.
     */
    @Override
    public TRcRoleMenuRecord setCreateTime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.create_time</code>.
     */
    @Override
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRcRoleMenu.T_RC_ROLE_MENU.ROLE_MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TRcRoleMenu.T_RC_ROLE_MENU.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRcRoleMenu.T_RC_ROLE_MENU.MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRcRoleMenu.T_RC_ROLE_MENU.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TRcRoleMenu.T_RC_ROLE_MENU.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return TRcRoleMenu.T_RC_ROLE_MENU.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return TRcRoleMenu.T_RC_ROLE_MENU.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRoleMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRoleMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value1(Integer value) {
        setRoleMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value3(Integer value) {
        setMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value5(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value7(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITRcRoleMenu from) {
        setRoleMenuId(from.getRoleMenuId());
        setRoleId(from.getRoleId());
        setMenuId(from.getMenuId());
        setStatus(from.getStatus());
        setOperator(from.getOperator());
        setUpdateTime(from.getUpdateTime());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITRcRoleMenu> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcRoleMenuRecord
     */
    public TRcRoleMenuRecord() {
        super(TRcRoleMenu.T_RC_ROLE_MENU);
    }

    /**
     * Create a detached, initialised TRcRoleMenuRecord
     */
    public TRcRoleMenuRecord(Integer roleMenuId, Integer roleId, Integer menuId, String status, String operator, LocalDateTime updateTime, LocalDateTime createTime) {
        super(TRcRoleMenu.T_RC_ROLE_MENU);

        set(0, roleMenuId);
        set(1, roleId);
        set(2, menuId);
        set(3, status);
        set(4, operator);
        set(5, updateTime);
        set(6, createTime);
    }

    public TRcRoleMenuRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
