/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcUserDept;
import org.cuber.upms.repo.tables.interfaces.ITRcUserDept;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserDeptRecord extends UpdatableRecordImpl<TRcUserDeptRecord> implements VertxPojo, Record7<Integer, Integer, Integer, String, String, LocalDateTime, LocalDateTime>, ITRcUserDept {

    private static final long serialVersionUID = -1551844714;

    /**
     * Setter for <code>upms.t_rc_user_dept.user_dept_id</code>.
     */
    @Override
    public TRcUserDeptRecord setUserDeptId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.user_dept_id</code>.
     */
    @Override
    public Integer getUserDeptId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.user_id</code>.
     */
    @Override
    public TRcUserDeptRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.user_id</code>.
     */
    @Override
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.dept_id</code>.
     */
    @Override
    public TRcUserDeptRecord setDeptId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.dept_id</code>.
     */
    @Override
    public Integer getDeptId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.status</code>.
     */
    @Override
    public TRcUserDeptRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.status</code>.
     */
    @Override
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.operator</code>.
     */
    @Override
    public TRcUserDeptRecord setOperator(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.operator</code>.
     */
    @Override
    public String getOperator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.update_time</code>.
     */
    @Override
    public TRcUserDeptRecord setUpdateTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.update_time</code>.
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.create_time</code>.
     */
    @Override
    public TRcUserDeptRecord setCreateTime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.create_time</code>.
     */
    @Override
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRcUserDept.T_RC_USER_DEPT.USER_DEPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TRcUserDept.T_RC_USER_DEPT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRcUserDept.T_RC_USER_DEPT.DEPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRcUserDept.T_RC_USER_DEPT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TRcUserDept.T_RC_USER_DEPT.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return TRcUserDept.T_RC_USER_DEPT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return TRcUserDept.T_RC_USER_DEPT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value1(Integer value) {
        setUserDeptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value3(Integer value) {
        setDeptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value5(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value7(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITRcUserDept from) {
        setUserDeptId(from.getUserDeptId());
        setUserId(from.getUserId());
        setDeptId(from.getDeptId());
        setStatus(from.getStatus());
        setOperator(from.getOperator());
        setUpdateTime(from.getUpdateTime());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITRcUserDept> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcUserDeptRecord
     */
    public TRcUserDeptRecord() {
        super(TRcUserDept.T_RC_USER_DEPT);
    }

    /**
     * Create a detached, initialised TRcUserDeptRecord
     */
    public TRcUserDeptRecord(Integer userDeptId, Integer userId, Integer deptId, String status, String operator, LocalDateTime updateTime, LocalDateTime createTime) {
        super(TRcUserDept.T_RC_USER_DEPT);

        set(0, userDeptId);
        set(1, userId);
        set(2, deptId);
        set(3, status);
        set(4, operator);
        set(5, updateTime);
        set(6, createTime);
    }

    public TRcUserDeptRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
