/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcUserRole;
import org.cuber.upms.repo.tables.interfaces.ITRcUserRole;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserRoleRecord extends UpdatableRecordImpl<TRcUserRoleRecord> implements VertxPojo, Record7<Integer, Integer, Integer, String, String, LocalDateTime, LocalDateTime>, ITRcUserRole {

    private static final long serialVersionUID = -490305167;

    /**
     * Setter for <code>upms.t_rc_user_role.user_role_id</code>.
     */
    @Override
    public TRcUserRoleRecord setUserRoleId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_role.user_role_id</code>.
     */
    @Override
    public Integer getUserRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.user_id</code>.
     */
    @Override
    public TRcUserRoleRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_role.user_id</code>.
     */
    @Override
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.role_id</code>.
     */
    @Override
    public TRcUserRoleRecord setRoleId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_role.role_id</code>.
     */
    @Override
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.status</code>.
     */
    @Override
    public TRcUserRoleRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_role.status</code>.
     */
    @Override
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.operator</code>.
     */
    @Override
    public TRcUserRoleRecord setOperator(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_role.operator</code>.
     */
    @Override
    public String getOperator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.update_time</code>.
     */
    @Override
    public TRcUserRoleRecord setUpdateTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_role.update_time</code>.
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.create_time</code>.
     */
    @Override
    public TRcUserRoleRecord setCreateTime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>upms.t_rc_user_role.create_time</code>.
     */
    @Override
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRcUserRole.T_RC_USER_ROLE.USER_ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TRcUserRole.T_RC_USER_ROLE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRcUserRole.T_RC_USER_ROLE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRcUserRole.T_RC_USER_ROLE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TRcUserRole.T_RC_USER_ROLE.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return TRcUserRole.T_RC_USER_ROLE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return TRcUserRole.T_RC_USER_ROLE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value1(Integer value) {
        setUserRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value5(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value7(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITRcUserRole from) {
        setUserRoleId(from.getUserRoleId());
        setUserId(from.getUserId());
        setRoleId(from.getRoleId());
        setStatus(from.getStatus());
        setOperator(from.getOperator());
        setUpdateTime(from.getUpdateTime());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITRcUserRole> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcUserRoleRecord
     */
    public TRcUserRoleRecord() {
        super(TRcUserRole.T_RC_USER_ROLE);
    }

    /**
     * Create a detached, initialised TRcUserRoleRecord
     */
    public TRcUserRoleRecord(Integer userRoleId, Integer userId, Integer roleId, String status, String operator, LocalDateTime updateTime, LocalDateTime createTime) {
        super(TRcUserRole.T_RC_USER_ROLE);

        set(0, userRoleId);
        set(1, userId);
        set(2, roleId);
        set(3, status);
        set(4, operator);
        set(5, updateTime);
        set(6, createTime);
    }

    public TRcUserRoleRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
