/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcUserRole;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserRoleRecord extends UpdatableRecordImpl<TRcUserRoleRecord> implements Record7<Integer, Integer, Integer, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1239138812;

    /**
     * Setter for <code>upms.t_rc_user_role.user_role_id</code>.
     */
    public void setUserRoleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_role.user_role_id</code>.
     */
    public Integer getUserRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_role.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_role.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_role.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.operator</code>.
     */
    public void setOperator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_role.operator</code>.
     */
    public String getOperator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_role.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>upms.t_rc_user_role.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_role.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRcUserRole.T_RC_USER_ROLE.USER_ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TRcUserRole.T_RC_USER_ROLE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRcUserRole.T_RC_USER_ROLE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRcUserRole.T_RC_USER_ROLE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TRcUserRole.T_RC_USER_ROLE.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TRcUserRole.T_RC_USER_ROLE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TRcUserRole.T_RC_USER_ROLE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value1(Integer value) {
        setUserRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value5(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRoleRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcUserRoleRecord
     */
    public TRcUserRoleRecord() {
        super(TRcUserRole.T_RC_USER_ROLE);
    }

    /**
     * Create a detached, initialised TRcUserRoleRecord
     */
    public TRcUserRoleRecord(Integer userRoleId, Integer userId, Integer roleId, String status, String operator, Timestamp updateTime, Timestamp createTime) {
        super(TRcUserRole.T_RC_USER_ROLE);

        set(0, userRoleId);
        set(1, userId);
        set(2, roleId);
        set(3, status);
        set(4, operator);
        set(5, updateTime);
        set(6, createTime);
    }
}
