/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcUser;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserRecord extends UpdatableRecordImpl<TRcUserRecord> implements Record18<Integer, String, String, String, String, String, Timestamp, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -818276492;

    /**
     * Setter for <code>upms.t_rc_user.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>upms.t_rc_user.avatar</code>. 头像url
     */
    public void setAvatar(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.avatar</code>. 头像url
     */
    public String getAvatar() {
        return (String) get(1);
    }

    /**
     * Setter for <code>upms.t_rc_user.user_name</code>. 登录名称
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.user_name</code>. 登录名称
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>upms.t_rc_user.password</code>. 登录密码
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.password</code>. 登录密码
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>upms.t_rc_user.salt</code>. 加密 salt
     */
    public void setSalt(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.salt</code>. 加密 salt
     */
    public String getSalt() {
        return (String) get(4);
    }

    /**
     * Setter for <code>upms.t_rc_user.full_name</code>. 名称
     */
    public void setFullName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.full_name</code>. 名称
     */
    public String getFullName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>upms.t_rc_user.birthday</code>. 生日
     */
    public void setBirthday(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.birthday</code>. 生日
     */
    public Timestamp getBirthday() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>upms.t_rc_user.user_scope</code>. 用户系统
     */
    public void setUserScope(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.user_scope</code>. 用户系统
     */
    public String getUserScope() {
        return (String) get(7);
    }

    /**
     * Setter for <code>upms.t_rc_user.sex</code>. 性别
     */
    public void setSex(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.sex</code>. 性别
     */
    public String getSex() {
        return (String) get(8);
    }

    /**
     * Setter for <code>upms.t_rc_user.email</code>. 邮箱
     */
    public void setEmail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>upms.t_rc_user.phone</code>. 电话
     */
    public void setPhone(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.phone</code>. 电话
     */
    public String getPhone() {
        return (String) get(10);
    }

    /**
     * Setter for <code>upms.t_rc_user.ding_user_id</code>. 钉钉用户ID
     */
    public void setDingUserId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.ding_user_id</code>. 钉钉用户ID
     */
    public String getDingUserId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>upms.t_rc_user.wechat_user_id</code>. 微信用户ID
     */
    public void setWechatUserId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.wechat_user_id</code>. 微信用户ID
     */
    public String getWechatUserId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>upms.t_rc_user.corp_number</code>. 员工号
     */
    public void setCorpNumber(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.corp_number</code>. 员工号
     */
    public String getCorpNumber() {
        return (String) get(13);
    }

    /**
     * Setter for <code>upms.t_rc_user.status</code>. 0 未激活 1 正常 2.离职  3.退休
     */
    public void setStatus(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.status</code>. 0 未激活 1 正常 2.离职  3.退休
     */
    public String getStatus() {
        return (String) get(14);
    }

    /**
     * Setter for <code>upms.t_rc_user.operator</code>.
     */
    public void setOperator(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.operator</code>.
     */
    public String getOperator() {
        return (String) get(15);
    }

    /**
     * Setter for <code>upms.t_rc_user.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>upms.t_rc_user.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>upms.t_rc_user.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, String, String, String, String, String, Timestamp, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, String, String, String, String, String, Timestamp, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRcUser.T_RC_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TRcUser.T_RC_USER.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TRcUser.T_RC_USER.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRcUser.T_RC_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TRcUser.T_RC_USER.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TRcUser.T_RC_USER.FULL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TRcUser.T_RC_USER.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TRcUser.T_RC_USER.USER_SCOPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TRcUser.T_RC_USER.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TRcUser.T_RC_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TRcUser.T_RC_USER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TRcUser.T_RC_USER.DING_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TRcUser.T_RC_USER.WECHAT_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TRcUser.T_RC_USER.CORP_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TRcUser.T_RC_USER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return TRcUser.T_RC_USER.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return TRcUser.T_RC_USER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return TRcUser.T_RC_USER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUserScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getDingUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getWechatUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getCorpNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUserScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDingUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getWechatUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCorpNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value2(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value3(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value5(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value6(String value) {
        setFullName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value7(Timestamp value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value8(String value) {
        setUserScope(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value9(String value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value10(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value11(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value12(String value) {
        setDingUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value13(String value) {
        setWechatUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value14(String value) {
        setCorpNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value15(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value16(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value17(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord value18(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, Timestamp value17, Timestamp value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcUserRecord
     */
    public TRcUserRecord() {
        super(TRcUser.T_RC_USER);
    }

    /**
     * Create a detached, initialised TRcUserRecord
     */
    public TRcUserRecord(Integer userId, String avatar, String userName, String password, String salt, String fullName, Timestamp birthday, String userScope, String sex, String email, String phone, String dingUserId, String wechatUserId, String corpNumber, String status, String operator, Timestamp updateTime, Timestamp createTime) {
        super(TRcUser.T_RC_USER);

        set(0, userId);
        set(1, avatar);
        set(2, userName);
        set(3, password);
        set(4, salt);
        set(5, fullName);
        set(6, birthday);
        set(7, userScope);
        set(8, sex);
        set(9, email);
        set(10, phone);
        set(11, dingUserId);
        set(12, wechatUserId);
        set(13, corpNumber);
        set(14, status);
        set(15, operator);
        set(16, updateTime);
        set(17, createTime);
    }
}
