/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcRoleMenu;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcRoleMenuRecord extends UpdatableRecordImpl<TRcRoleMenuRecord> implements Record7<Integer, Integer, Integer, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1863643864;

    /**
     * Setter for <code>upms.t_rc_role_menu.role_menu_id</code>.
     */
    public void setRoleMenuId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.role_menu_id</code>.
     */
    public Integer getRoleMenuId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.menu_id</code>.
     */
    public void setMenuId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.menu_id</code>.
     */
    public Integer getMenuId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.operator</code>.
     */
    public void setOperator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.operator</code>.
     */
    public String getOperator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>upms.t_rc_role_menu.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>upms.t_rc_role_menu.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRcRoleMenu.T_RC_ROLE_MENU.ROLE_MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TRcRoleMenu.T_RC_ROLE_MENU.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRcRoleMenu.T_RC_ROLE_MENU.MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRcRoleMenu.T_RC_ROLE_MENU.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TRcRoleMenu.T_RC_ROLE_MENU.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TRcRoleMenu.T_RC_ROLE_MENU.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TRcRoleMenu.T_RC_ROLE_MENU.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRoleMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRoleMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value1(Integer value) {
        setRoleMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value3(Integer value) {
        setMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value5(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcRoleMenuRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcRoleMenuRecord
     */
    public TRcRoleMenuRecord() {
        super(TRcRoleMenu.T_RC_ROLE_MENU);
    }

    /**
     * Create a detached, initialised TRcRoleMenuRecord
     */
    public TRcRoleMenuRecord(Integer roleMenuId, Integer roleId, Integer menuId, String status, String operator, Timestamp updateTime, Timestamp createTime) {
        super(TRcRoleMenu.T_RC_ROLE_MENU);

        set(0, roleMenuId);
        set(1, roleId);
        set(2, menuId);
        set(3, status);
        set(4, operator);
        set(5, updateTime);
        set(6, createTime);
    }
}
