/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcUserDept;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserDeptRecord extends UpdatableRecordImpl<TRcUserDeptRecord> implements Record7<Integer, Integer, Integer, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 465706283;

    /**
     * Setter for <code>upms.t_rc_user_dept.user_dept_id</code>.
     */
    public void setUserDeptId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.user_dept_id</code>.
     */
    public Integer getUserDeptId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.dept_id</code>.
     */
    public void setDeptId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.dept_id</code>.
     */
    public Integer getDeptId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.operator</code>.
     */
    public void setOperator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.operator</code>.
     */
    public String getOperator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>upms.t_rc_user_dept.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>upms.t_rc_user_dept.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRcUserDept.T_RC_USER_DEPT.USER_DEPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TRcUserDept.T_RC_USER_DEPT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRcUserDept.T_RC_USER_DEPT.DEPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRcUserDept.T_RC_USER_DEPT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TRcUserDept.T_RC_USER_DEPT.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TRcUserDept.T_RC_USER_DEPT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TRcUserDept.T_RC_USER_DEPT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDeptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value1(Integer value) {
        setUserDeptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value3(Integer value) {
        setDeptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value5(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRcUserDeptRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcUserDeptRecord
     */
    public TRcUserDeptRecord() {
        super(TRcUserDept.T_RC_USER_DEPT);
    }

    /**
     * Create a detached, initialised TRcUserDeptRecord
     */
    public TRcUserDeptRecord(Integer userDeptId, Integer userId, Integer deptId, String status, String operator, Timestamp updateTime, Timestamp createTime) {
        super(TRcUserDept.T_RC_USER_DEPT);

        set(0, userDeptId);
        set(1, userId);
        set(2, deptId);
        set(3, status);
        set(4, operator);
        set(5, updateTime);
        set(6, createTime);
    }
}
