/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.interfaces.ITRcDept;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcDept implements VertxPojo, ITRcDept {

    private static final long serialVersionUID = -1717835347;

    private Integer       deptId;
    private String        simpleName;
    private String        fullName;
    private String        tips;
    private Integer       pDeptId;
    private String        status;
    private String        operator;
    private LocalDateTime updateTime;
    private LocalDateTime createTime;

    public TRcDept() {}

    public TRcDept(TRcDept value) {
        this.deptId = value.deptId;
        this.simpleName = value.simpleName;
        this.fullName = value.fullName;
        this.tips = value.tips;
        this.pDeptId = value.pDeptId;
        this.status = value.status;
        this.operator = value.operator;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public TRcDept(
        Integer       deptId,
        String        simpleName,
        String        fullName,
        String        tips,
        Integer       pDeptId,
        String        status,
        String        operator,
        LocalDateTime updateTime,
        LocalDateTime createTime
    ) {
        this.deptId = deptId;
        this.simpleName = simpleName;
        this.fullName = fullName;
        this.tips = tips;
        this.pDeptId = pDeptId;
        this.status = status;
        this.operator = operator;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    @Override
    public Integer getDeptId() {
        return this.deptId;
    }

    @Override
    public TRcDept setDeptId(Integer deptId) {
        this.deptId = deptId;
        return this;
    }

    @Override
    public String getSimpleName() {
        return this.simpleName;
    }

    @Override
    public TRcDept setSimpleName(String simpleName) {
        this.simpleName = simpleName;
        return this;
    }

    @Override
    public String getFullName() {
        return this.fullName;
    }

    @Override
    public TRcDept setFullName(String fullName) {
        this.fullName = fullName;
        return this;
    }

    @Override
    public String getTips() {
        return this.tips;
    }

    @Override
    public TRcDept setTips(String tips) {
        this.tips = tips;
        return this;
    }

    @Override
    public Integer getPDeptId() {
        return this.pDeptId;
    }

    @Override
    public TRcDept setPDeptId(Integer pDeptId) {
        this.pDeptId = pDeptId;
        return this;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public TRcDept setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public String getOperator() {
        return this.operator;
    }

    @Override
    public TRcDept setOperator(String operator) {
        this.operator = operator;
        return this;
    }

    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public TRcDept setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    @Override
    public TRcDept setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRcDept (");

        sb.append(deptId);
        sb.append(", ").append(simpleName);
        sb.append(", ").append(fullName);
        sb.append(", ").append(tips);
        sb.append(", ").append(pDeptId);
        sb.append(", ").append(status);
        sb.append(", ").append(operator);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITRcDept from) {
        setDeptId(from.getDeptId());
        setSimpleName(from.getSimpleName());
        setFullName(from.getFullName());
        setTips(from.getTips());
        setPDeptId(from.getPDeptId());
        setStatus(from.getStatus());
        setOperator(from.getOperator());
        setUpdateTime(from.getUpdateTime());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITRcDept> E into(E into) {
        into.from(this);
        return into;
    }

    public TRcDept(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
