/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcMenu implements Serializable {

    private static final long serialVersionUID = 748770015;

    private Integer   menuId;
    private String    code;
    private String    pCode;
    private String    name;
    private String    url;
    private String    menuType;
    private String    menuScope;
    private Integer   level;
    private Integer   sort;
    private String    status;
    private String    operator;
    private Timestamp updateTime;
    private Timestamp createTime;

    public TRcMenu() {}

    public TRcMenu(TRcMenu value) {
        this.menuId = value.menuId;
        this.code = value.code;
        this.pCode = value.pCode;
        this.name = value.name;
        this.url = value.url;
        this.menuType = value.menuType;
        this.menuScope = value.menuScope;
        this.level = value.level;
        this.sort = value.sort;
        this.status = value.status;
        this.operator = value.operator;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public TRcMenu(
        Integer   menuId,
        String    code,
        String    pCode,
        String    name,
        String    url,
        String    menuType,
        String    menuScope,
        Integer   level,
        Integer   sort,
        String    status,
        String    operator,
        Timestamp updateTime,
        Timestamp createTime
    ) {
        this.menuId = menuId;
        this.code = code;
        this.pCode = pCode;
        this.name = name;
        this.url = url;
        this.menuType = menuType;
        this.menuScope = menuScope;
        this.level = level;
        this.sort = sort;
        this.status = status;
        this.operator = operator;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public Integer getMenuId() {
        return this.menuId;
    }

    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getPCode() {
        return this.pCode;
    }

    public void setPCode(String pCode) {
        this.pCode = pCode;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getMenuType() {
        return this.menuType;
    }

    public void setMenuType(String menuType) {
        this.menuType = menuType;
    }

    public String getMenuScope() {
        return this.menuScope;
    }

    public void setMenuScope(String menuScope) {
        this.menuScope = menuScope;
    }

    public Integer getLevel() {
        return this.level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getOperator() {
        return this.operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRcMenu (");

        sb.append(menuId);
        sb.append(", ").append(code);
        sb.append(", ").append(pCode);
        sb.append(", ").append(name);
        sb.append(", ").append(url);
        sb.append(", ").append(menuType);
        sb.append(", ").append(menuScope);
        sb.append(", ").append(level);
        sb.append(", ").append(sort);
        sb.append(", ").append(status);
        sb.append(", ").append(operator);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
