/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.interfaces.ITRcUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUser implements VertxPojo, ITRcUser {

    private static final long serialVersionUID = -781346705;

    private Integer       userId;
    private String        avatar;
    private String        userName;
    private String        password;
    private String        salt;
    private String        fullName;
    private LocalDateTime birthday;
    private String        userScope;
    private String        sex;
    private String        email;
    private String        phone;
    private String        dingUserId;
    private String        wechatUserId;
    private String        corpNumber;
    private String        status;
    private String        operator;
    private LocalDateTime updateTime;
    private LocalDateTime createTime;

    public TRcUser() {}

    public TRcUser(TRcUser value) {
        this.userId = value.userId;
        this.avatar = value.avatar;
        this.userName = value.userName;
        this.password = value.password;
        this.salt = value.salt;
        this.fullName = value.fullName;
        this.birthday = value.birthday;
        this.userScope = value.userScope;
        this.sex = value.sex;
        this.email = value.email;
        this.phone = value.phone;
        this.dingUserId = value.dingUserId;
        this.wechatUserId = value.wechatUserId;
        this.corpNumber = value.corpNumber;
        this.status = value.status;
        this.operator = value.operator;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public TRcUser(
        Integer       userId,
        String        avatar,
        String        userName,
        String        password,
        String        salt,
        String        fullName,
        LocalDateTime birthday,
        String        userScope,
        String        sex,
        String        email,
        String        phone,
        String        dingUserId,
        String        wechatUserId,
        String        corpNumber,
        String        status,
        String        operator,
        LocalDateTime updateTime,
        LocalDateTime createTime
    ) {
        this.userId = userId;
        this.avatar = avatar;
        this.userName = userName;
        this.password = password;
        this.salt = salt;
        this.fullName = fullName;
        this.birthday = birthday;
        this.userScope = userScope;
        this.sex = sex;
        this.email = email;
        this.phone = phone;
        this.dingUserId = dingUserId;
        this.wechatUserId = wechatUserId;
        this.corpNumber = corpNumber;
        this.status = status;
        this.operator = operator;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    @Override
    public Integer getUserId() {
        return this.userId;
    }

    @Override
    public TRcUser setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public String getAvatar() {
        return this.avatar;
    }

    @Override
    public TRcUser setAvatar(String avatar) {
        this.avatar = avatar;
        return this;
    }

    @Override
    public String getUserName() {
        return this.userName;
    }

    @Override
    public TRcUser setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public TRcUser setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public String getSalt() {
        return this.salt;
    }

    @Override
    public TRcUser setSalt(String salt) {
        this.salt = salt;
        return this;
    }

    @Override
    public String getFullName() {
        return this.fullName;
    }

    @Override
    public TRcUser setFullName(String fullName) {
        this.fullName = fullName;
        return this;
    }

    @Override
    public LocalDateTime getBirthday() {
        return this.birthday;
    }

    @Override
    public TRcUser setBirthday(LocalDateTime birthday) {
        this.birthday = birthday;
        return this;
    }

    @Override
    public String getUserScope() {
        return this.userScope;
    }

    @Override
    public TRcUser setUserScope(String userScope) {
        this.userScope = userScope;
        return this;
    }

    @Override
    public String getSex() {
        return this.sex;
    }

    @Override
    public TRcUser setSex(String sex) {
        this.sex = sex;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public TRcUser setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getPhone() {
        return this.phone;
    }

    @Override
    public TRcUser setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    @Override
    public String getDingUserId() {
        return this.dingUserId;
    }

    @Override
    public TRcUser setDingUserId(String dingUserId) {
        this.dingUserId = dingUserId;
        return this;
    }

    @Override
    public String getWechatUserId() {
        return this.wechatUserId;
    }

    @Override
    public TRcUser setWechatUserId(String wechatUserId) {
        this.wechatUserId = wechatUserId;
        return this;
    }

    @Override
    public String getCorpNumber() {
        return this.corpNumber;
    }

    @Override
    public TRcUser setCorpNumber(String corpNumber) {
        this.corpNumber = corpNumber;
        return this;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public TRcUser setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public String getOperator() {
        return this.operator;
    }

    @Override
    public TRcUser setOperator(String operator) {
        this.operator = operator;
        return this;
    }

    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public TRcUser setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    @Override
    public TRcUser setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRcUser (");

        sb.append(userId);
        sb.append(", ").append(avatar);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(salt);
        sb.append(", ").append(fullName);
        sb.append(", ").append(birthday);
        sb.append(", ").append(userScope);
        sb.append(", ").append(sex);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(dingUserId);
        sb.append(", ").append(wechatUserId);
        sb.append(", ").append(corpNumber);
        sb.append(", ").append(status);
        sb.append(", ").append(operator);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITRcUser from) {
        setUserId(from.getUserId());
        setAvatar(from.getAvatar());
        setUserName(from.getUserName());
        setPassword(from.getPassword());
        setSalt(from.getSalt());
        setFullName(from.getFullName());
        setBirthday(from.getBirthday());
        setUserScope(from.getUserScope());
        setSex(from.getSex());
        setEmail(from.getEmail());
        setPhone(from.getPhone());
        setDingUserId(from.getDingUserId());
        setWechatUserId(from.getWechatUserId());
        setCorpNumber(from.getCorpNumber());
        setStatus(from.getStatus());
        setOperator(from.getOperator());
        setUpdateTime(from.getUpdateTime());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITRcUser> E into(E into) {
        into.from(this);
        return into;
    }

    public TRcUser(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
