/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.interfaces.ITRcUserRole;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRcUserRole implements VertxPojo, ITRcUserRole {

    private static final long serialVersionUID = 401896047;

    private Integer       userRoleId;
    private Integer       userId;
    private Integer       roleId;
    private String        status;
    private String        operator;
    private LocalDateTime updateTime;
    private LocalDateTime createTime;

    public TRcUserRole() {}

    public TRcUserRole(TRcUserRole value) {
        this.userRoleId = value.userRoleId;
        this.userId = value.userId;
        this.roleId = value.roleId;
        this.status = value.status;
        this.operator = value.operator;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public TRcUserRole(
        Integer       userRoleId,
        Integer       userId,
        Integer       roleId,
        String        status,
        String        operator,
        LocalDateTime updateTime,
        LocalDateTime createTime
    ) {
        this.userRoleId = userRoleId;
        this.userId = userId;
        this.roleId = roleId;
        this.status = status;
        this.operator = operator;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    @Override
    public Integer getUserRoleId() {
        return this.userRoleId;
    }

    @Override
    public TRcUserRole setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
        return this;
    }

    @Override
    public Integer getUserId() {
        return this.userId;
    }

    @Override
    public TRcUserRole setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public Integer getRoleId() {
        return this.roleId;
    }

    @Override
    public TRcUserRole setRoleId(Integer roleId) {
        this.roleId = roleId;
        return this;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public TRcUserRole setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public String getOperator() {
        return this.operator;
    }

    @Override
    public TRcUserRole setOperator(String operator) {
        this.operator = operator;
        return this;
    }

    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public TRcUserRole setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    @Override
    public TRcUserRole setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRcUserRole (");

        sb.append(userRoleId);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);
        sb.append(", ").append(status);
        sb.append(", ").append(operator);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITRcUserRole from) {
        setUserRoleId(from.getUserRoleId());
        setUserId(from.getUserId());
        setRoleId(from.getRoleId());
        setStatus(from.getStatus());
        setOperator(from.getOperator());
        setUpdateTime(from.getUpdateTime());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITRcUserRole> E into(E into) {
        into.from(this);
        return into;
    }

    public TRcUserRole(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
