/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo;


import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcDept;
import org.cuber.upms.repo.tables.TRcMenu;
import org.cuber.upms.repo.tables.TRcRole;
import org.cuber.upms.repo.tables.TRcRoleMenu;
import org.cuber.upms.repo.tables.TRcUser;
import org.cuber.upms.repo.tables.TRcUserDept;
import org.cuber.upms.repo.tables.TRcUserRole;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>upms</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_RC_DEPT_PKEY = Indexes0.T_RC_DEPT_PKEY;
    public static final Index IDX_UNQ_RC_MENU_CODE = Indexes0.IDX_UNQ_RC_MENU_CODE;
    public static final Index T_RC_MENU_PKEY = Indexes0.T_RC_MENU_PKEY;
    public static final Index IDX_UNQ_RC_ROLE_NAME = Indexes0.IDX_UNQ_RC_ROLE_NAME;
    public static final Index IDX_UNQ_RC_ROLE_ROLE = Indexes0.IDX_UNQ_RC_ROLE_ROLE;
    public static final Index T_RC_ROLE_PKEY = Indexes0.T_RC_ROLE_PKEY;
    public static final Index T_RC_ROLE_MENU_PKEY = Indexes0.T_RC_ROLE_MENU_PKEY;
    public static final Index IDX_UNQ_RC_USER_USERNAME = Indexes0.IDX_UNQ_RC_USER_USERNAME;
    public static final Index T_RC_USER_PKEY = Indexes0.T_RC_USER_PKEY;
    public static final Index T_RC_USER_DEPT_PKEY = Indexes0.T_RC_USER_DEPT_PKEY;
    public static final Index T_RC_USER_ROLE_PKEY = Indexes0.T_RC_USER_ROLE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_RC_DEPT_PKEY = Internal.createIndex("t_rc_dept_pkey", TRcDept.T_RC_DEPT, new OrderField[] { TRcDept.T_RC_DEPT.DEPT_ID }, true);
        public static Index IDX_UNQ_RC_MENU_CODE = Internal.createIndex("idx_unq_rc_menu_code", TRcMenu.T_RC_MENU, new OrderField[] { TRcMenu.T_RC_MENU.CODE }, true);
        public static Index T_RC_MENU_PKEY = Internal.createIndex("t_rc_menu_pkey", TRcMenu.T_RC_MENU, new OrderField[] { TRcMenu.T_RC_MENU.MENU_ID }, true);
        public static Index IDX_UNQ_RC_ROLE_NAME = Internal.createIndex("idx_unq_rc_role_name", TRcRole.T_RC_ROLE, new OrderField[] { TRcRole.T_RC_ROLE.NAME }, true);
        public static Index IDX_UNQ_RC_ROLE_ROLE = Internal.createIndex("idx_unq_rc_role_role", TRcRole.T_RC_ROLE, new OrderField[] { TRcRole.T_RC_ROLE.ROLE }, true);
        public static Index T_RC_ROLE_PKEY = Internal.createIndex("t_rc_role_pkey", TRcRole.T_RC_ROLE, new OrderField[] { TRcRole.T_RC_ROLE.ROLE_ID }, true);
        public static Index T_RC_ROLE_MENU_PKEY = Internal.createIndex("t_rc_role_menu_pkey", TRcRoleMenu.T_RC_ROLE_MENU, new OrderField[] { TRcRoleMenu.T_RC_ROLE_MENU.ROLE_MENU_ID }, true);
        public static Index IDX_UNQ_RC_USER_USERNAME = Internal.createIndex("idx_unq_rc_user_username", TRcUser.T_RC_USER, new OrderField[] { TRcUser.T_RC_USER.USER_NAME }, true);
        public static Index T_RC_USER_PKEY = Internal.createIndex("t_rc_user_pkey", TRcUser.T_RC_USER, new OrderField[] { TRcUser.T_RC_USER.USER_ID }, true);
        public static Index T_RC_USER_DEPT_PKEY = Internal.createIndex("t_rc_user_dept_pkey", TRcUserDept.T_RC_USER_DEPT, new OrderField[] { TRcUserDept.T_RC_USER_DEPT.USER_DEPT_ID }, true);
        public static Index T_RC_USER_ROLE_PKEY = Internal.createIndex("t_rc_user_role_pkey", TRcUserRole.T_RC_USER_ROLE, new OrderField[] { TRcUserRole.T_RC_USER_ROLE.USER_ROLE_ID }, true);
    }
}
