/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo;


import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcDept;
import org.cuber.upms.repo.tables.TRcMenu;
import org.cuber.upms.repo.tables.TRcRole;
import org.cuber.upms.repo.tables.TRcRoleMenu;
import org.cuber.upms.repo.tables.TRcUser;
import org.cuber.upms.repo.tables.TRcUserDept;
import org.cuber.upms.repo.tables.TRcUserRole;
import org.cuber.upms.repo.tables.records.TRcDeptRecord;
import org.cuber.upms.repo.tables.records.TRcMenuRecord;
import org.cuber.upms.repo.tables.records.TRcRoleMenuRecord;
import org.cuber.upms.repo.tables.records.TRcRoleRecord;
import org.cuber.upms.repo.tables.records.TRcUserDeptRecord;
import org.cuber.upms.repo.tables.records.TRcUserRecord;
import org.cuber.upms.repo.tables.records.TRcUserRoleRecord;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>upms</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TRcDeptRecord, Integer> IDENTITY_T_RC_DEPT = Identities0.IDENTITY_T_RC_DEPT;
    public static final Identity<TRcMenuRecord, Integer> IDENTITY_T_RC_MENU = Identities0.IDENTITY_T_RC_MENU;
    public static final Identity<TRcRoleRecord, Integer> IDENTITY_T_RC_ROLE = Identities0.IDENTITY_T_RC_ROLE;
    public static final Identity<TRcRoleMenuRecord, Integer> IDENTITY_T_RC_ROLE_MENU = Identities0.IDENTITY_T_RC_ROLE_MENU;
    public static final Identity<TRcUserRecord, Integer> IDENTITY_T_RC_USER = Identities0.IDENTITY_T_RC_USER;
    public static final Identity<TRcUserDeptRecord, Integer> IDENTITY_T_RC_USER_DEPT = Identities0.IDENTITY_T_RC_USER_DEPT;
    public static final Identity<TRcUserRoleRecord, Integer> IDENTITY_T_RC_USER_ROLE = Identities0.IDENTITY_T_RC_USER_ROLE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TRcDeptRecord> T_RC_DEPT_PKEY = UniqueKeys0.T_RC_DEPT_PKEY;
    public static final UniqueKey<TRcMenuRecord> T_RC_MENU_PKEY = UniqueKeys0.T_RC_MENU_PKEY;
    public static final UniqueKey<TRcRoleRecord> T_RC_ROLE_PKEY = UniqueKeys0.T_RC_ROLE_PKEY;
    public static final UniqueKey<TRcRoleMenuRecord> T_RC_ROLE_MENU_PKEY = UniqueKeys0.T_RC_ROLE_MENU_PKEY;
    public static final UniqueKey<TRcUserRecord> T_RC_USER_PKEY = UniqueKeys0.T_RC_USER_PKEY;
    public static final UniqueKey<TRcUserDeptRecord> T_RC_USER_DEPT_PKEY = UniqueKeys0.T_RC_USER_DEPT_PKEY;
    public static final UniqueKey<TRcUserRoleRecord> T_RC_USER_ROLE_PKEY = UniqueKeys0.T_RC_USER_ROLE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TRcDeptRecord, Integer> IDENTITY_T_RC_DEPT = Internal.createIdentity(TRcDept.T_RC_DEPT, TRcDept.T_RC_DEPT.DEPT_ID);
        public static Identity<TRcMenuRecord, Integer> IDENTITY_T_RC_MENU = Internal.createIdentity(TRcMenu.T_RC_MENU, TRcMenu.T_RC_MENU.MENU_ID);
        public static Identity<TRcRoleRecord, Integer> IDENTITY_T_RC_ROLE = Internal.createIdentity(TRcRole.T_RC_ROLE, TRcRole.T_RC_ROLE.ROLE_ID);
        public static Identity<TRcRoleMenuRecord, Integer> IDENTITY_T_RC_ROLE_MENU = Internal.createIdentity(TRcRoleMenu.T_RC_ROLE_MENU, TRcRoleMenu.T_RC_ROLE_MENU.ROLE_MENU_ID);
        public static Identity<TRcUserRecord, Integer> IDENTITY_T_RC_USER = Internal.createIdentity(TRcUser.T_RC_USER, TRcUser.T_RC_USER.USER_ID);
        public static Identity<TRcUserDeptRecord, Integer> IDENTITY_T_RC_USER_DEPT = Internal.createIdentity(TRcUserDept.T_RC_USER_DEPT, TRcUserDept.T_RC_USER_DEPT.USER_DEPT_ID);
        public static Identity<TRcUserRoleRecord, Integer> IDENTITY_T_RC_USER_ROLE = Internal.createIdentity(TRcUserRole.T_RC_USER_ROLE, TRcUserRole.T_RC_USER_ROLE.USER_ROLE_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<TRcDeptRecord> T_RC_DEPT_PKEY = Internal.createUniqueKey(TRcDept.T_RC_DEPT, "t_rc_dept_pkey", TRcDept.T_RC_DEPT.DEPT_ID);
        public static final UniqueKey<TRcMenuRecord> T_RC_MENU_PKEY = Internal.createUniqueKey(TRcMenu.T_RC_MENU, "t_rc_menu_pkey", TRcMenu.T_RC_MENU.MENU_ID);
        public static final UniqueKey<TRcRoleRecord> T_RC_ROLE_PKEY = Internal.createUniqueKey(TRcRole.T_RC_ROLE, "t_rc_role_pkey", TRcRole.T_RC_ROLE.ROLE_ID);
        public static final UniqueKey<TRcRoleMenuRecord> T_RC_ROLE_MENU_PKEY = Internal.createUniqueKey(TRcRoleMenu.T_RC_ROLE_MENU, "t_rc_role_menu_pkey", TRcRoleMenu.T_RC_ROLE_MENU.ROLE_MENU_ID);
        public static final UniqueKey<TRcUserRecord> T_RC_USER_PKEY = Internal.createUniqueKey(TRcUser.T_RC_USER, "t_rc_user_pkey", TRcUser.T_RC_USER.USER_ID);
        public static final UniqueKey<TRcUserDeptRecord> T_RC_USER_DEPT_PKEY = Internal.createUniqueKey(TRcUserDept.T_RC_USER_DEPT, "t_rc_user_dept_pkey", TRcUserDept.T_RC_USER_DEPT.USER_DEPT_ID);
        public static final UniqueKey<TRcUserRoleRecord> T_RC_USER_ROLE_PKEY = Internal.createUniqueKey(TRcUserRole.T_RC_USER_ROLE, "t_rc_user_role_pkey", TRcUserRole.T_RC_USER_ROLE.USER_ROLE_ID);
    }
}
