/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in upms
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>upms.t_rc_dept_dept_id_seq</code>
     */
    public static final Sequence<Integer> T_RC_DEPT_DEPT_ID_SEQ = new SequenceImpl<Integer>("t_rc_dept_dept_id_seq", Upms.UPMS, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>upms.t_rc_menu_menu_id_seq</code>
     */
    public static final Sequence<Integer> T_RC_MENU_MENU_ID_SEQ = new SequenceImpl<Integer>("t_rc_menu_menu_id_seq", Upms.UPMS, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>upms.t_rc_role_menu_role_menu_id_seq</code>
     */
    public static final Sequence<Integer> T_RC_ROLE_MENU_ROLE_MENU_ID_SEQ = new SequenceImpl<Integer>("t_rc_role_menu_role_menu_id_seq", Upms.UPMS, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>upms.t_rc_role_role_id_seq</code>
     */
    public static final Sequence<Integer> T_RC_ROLE_ROLE_ID_SEQ = new SequenceImpl<Integer>("t_rc_role_role_id_seq", Upms.UPMS, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>upms.t_rc_user_dept_user_dept_id_seq</code>
     */
    public static final Sequence<Integer> T_RC_USER_DEPT_USER_DEPT_ID_SEQ = new SequenceImpl<Integer>("t_rc_user_dept_user_dept_id_seq", Upms.UPMS, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>upms.t_rc_user_role_user_role_id_seq</code>
     */
    public static final Sequence<Integer> T_RC_USER_ROLE_USER_ROLE_ID_SEQ = new SequenceImpl<Integer>("t_rc_user_role_user_role_id_seq", Upms.UPMS, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>upms.t_rc_user_user_id_seq</code>
     */
    public static final Sequence<Integer> T_RC_USER_USER_ID_SEQ = new SequenceImpl<Integer>("t_rc_user_user_id_seq", Upms.UPMS, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
