/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo;


import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcDept;
import org.cuber.upms.repo.tables.TRcMenu;
import org.cuber.upms.repo.tables.TRcRole;
import org.cuber.upms.repo.tables.TRcRoleMenu;
import org.cuber.upms.repo.tables.TRcUser;
import org.cuber.upms.repo.tables.TRcUserDept;
import org.cuber.upms.repo.tables.TRcUserRole;


/**
 * Convenience access to all tables in upms
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>upms.t_rc_dept</code>.
     */
    public static final TRcDept T_RC_DEPT = org.cuber.upms.repo.tables.TRcDept.T_RC_DEPT;

    /**
     * The table <code>upms.t_rc_menu</code>.
     */
    public static final TRcMenu T_RC_MENU = org.cuber.upms.repo.tables.TRcMenu.T_RC_MENU;

    /**
     * The table <code>upms.t_rc_role</code>.
     */
    public static final TRcRole T_RC_ROLE = org.cuber.upms.repo.tables.TRcRole.T_RC_ROLE;

    /**
     * The table <code>upms.t_rc_role_menu</code>.
     */
    public static final TRcRoleMenu T_RC_ROLE_MENU = org.cuber.upms.repo.tables.TRcRoleMenu.T_RC_ROLE_MENU;

    /**
     * The table <code>upms.t_rc_user</code>.
     */
    public static final TRcUser T_RC_USER = org.cuber.upms.repo.tables.TRcUser.T_RC_USER;

    /**
     * The table <code>upms.t_rc_user_dept</code>.
     */
    public static final TRcUserDept T_RC_USER_DEPT = org.cuber.upms.repo.tables.TRcUserDept.T_RC_USER_DEPT;

    /**
     * The table <code>upms.t_rc_user_role</code>.
     */
    public static final TRcUserRole T_RC_USER_ROLE = org.cuber.upms.repo.tables.TRcUserRole.T_RC_USER_ROLE;
}
