/*
 * This file is generated by jOOQ.
*/
package org.cuber.upms.repo;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.cuber.upms.repo.tables.TRcDept;
import org.cuber.upms.repo.tables.TRcMenu;
import org.cuber.upms.repo.tables.TRcRole;
import org.cuber.upms.repo.tables.TRcRoleMenu;
import org.cuber.upms.repo.tables.TRcUser;
import org.cuber.upms.repo.tables.TRcUserDept;
import org.cuber.upms.repo.tables.TRcUserRole;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Upms extends SchemaImpl {

    private static final long serialVersionUID = 1168625236;

    /**
     * The reference instance of <code>upms</code>
     */
    public static final Upms UPMS = new Upms();

    /**
     * The table <code>upms.t_rc_dept</code>.
     */
    public final TRcDept T_RC_DEPT = org.cuber.upms.repo.tables.TRcDept.T_RC_DEPT;

    /**
     * The table <code>upms.t_rc_menu</code>.
     */
    public final TRcMenu T_RC_MENU = org.cuber.upms.repo.tables.TRcMenu.T_RC_MENU;

    /**
     * The table <code>upms.t_rc_role</code>.
     */
    public final TRcRole T_RC_ROLE = org.cuber.upms.repo.tables.TRcRole.T_RC_ROLE;

    /**
     * The table <code>upms.t_rc_role_menu</code>.
     */
    public final TRcRoleMenu T_RC_ROLE_MENU = org.cuber.upms.repo.tables.TRcRoleMenu.T_RC_ROLE_MENU;

    /**
     * The table <code>upms.t_rc_user</code>.
     */
    public final TRcUser T_RC_USER = org.cuber.upms.repo.tables.TRcUser.T_RC_USER;

    /**
     * The table <code>upms.t_rc_user_dept</code>.
     */
    public final TRcUserDept T_RC_USER_DEPT = org.cuber.upms.repo.tables.TRcUserDept.T_RC_USER_DEPT;

    /**
     * The table <code>upms.t_rc_user_role</code>.
     */
    public final TRcUserRole T_RC_USER_ROLE = org.cuber.upms.repo.tables.TRcUserRole.T_RC_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Upms() {
        super("upms", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.T_RC_DEPT_DEPT_ID_SEQ,
            Sequences.T_RC_MENU_MENU_ID_SEQ,
            Sequences.T_RC_ROLE_MENU_ROLE_MENU_ID_SEQ,
            Sequences.T_RC_ROLE_ROLE_ID_SEQ,
            Sequences.T_RC_USER_DEPT_USER_DEPT_ID_SEQ,
            Sequences.T_RC_USER_ROLE_USER_ROLE_ID_SEQ,
            Sequences.T_RC_USER_USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TRcDept.T_RC_DEPT,
            TRcMenu.T_RC_MENU,
            TRcRole.T_RC_ROLE,
            TRcRoleMenu.T_RC_ROLE_MENU,
            TRcUser.T_RC_USER,
            TRcUserDept.T_RC_USER_DEPT,
            TRcUserRole.T_RC_USER_ROLE);
    }
}
